"""Static equipment catalog data derived from design guidance."""
from __future__ import annotations

from typing import Dict, List, Sequence


EquipmentDefinition = Dict[str, object]


def _weapon(
    *,
    id: str,
    name: str,
    ship_class: str,
    price: int,
    durability: int,
    stats: Dict[str, float],
    upgrades: Sequence[str],
    description: str,
    tags: Sequence[str] = (),
) -> EquipmentDefinition:
    return {
        "id": id,
        "name": name,
        "slot_family": "weapon",
        "ship_class": ship_class,
        "level": 1,
        "durability": durability,
        "durability_max": durability,
        "price": price,
        "stats": stats,
        "upgrades": tuple(upgrades),
        "description": description,
        "tags": tuple(tags),
    }


def _module(
    *,
    id: str,
    name: str,
    slot_family: str,
    ship_class: str,
    price: int,
    durability: int,
    stats: Dict[str, float],
    upgrades: Sequence[str],
    description: str,
    tags: Sequence[str] = (),
) -> EquipmentDefinition:
    return {
        "id": id,
        "name": name,
        "slot_family": slot_family,
        "ship_class": ship_class,
        "level": 1,
        "durability": durability,
        "durability_max": durability,
        "price": price,
        "stats": stats,
        "upgrades": tuple(upgrades),
        "description": description,
        "tags": tuple(tags),
    }


EQUIPMENT_ITEMS: List[EquipmentDefinition] = [
    # Strike-class weapons -------------------------------------------------
    _weapon(
        id="mec_a6",
        name="MEC-A6 'Fang'",
        ship_class="Strike",
        price=10_000,
        durability=6_000,
        stats={
            "damage_min": 1.0,
            "damage_max": 10.0,
            "armor_piercing": 5.0,
            "range_min": 0.0,
            "range_max": 750.0,
            "optimal_range": 300.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 0.5,
            "power": 1.0,
            "firing_arc": 75.0,
        },
        upgrades=("damage", "optimal_range"),
        description="General-purpose Strike autocannon balancing reach and control.",
        tags=("balanced", "rapid_fire"),
    ),
    _weapon(
        id="fc_39b_blackjack",
        name="FC-39B 'Blackjack'",
        ship_class="Strike",
        price=62_000,
        durability=6_000,
        stats={
            "damage_min": 26.5,
            "damage_max": 42.4,
            "armor_piercing": 0.0,
            "range_min": 0.0,
            "range_max": 350.0,
            "optimal_range": 150.0,
            "accuracy": 450.0,
            "critical_offense": 110.0,
            "reload": 0.8,
            "power": 4.5,
            "firing_arc": 40.0,
        },
        upgrades=("damage",),
        description="Raven-exclusive flechette gun delivering brutal close-range burst damage.",
        tags=("close_quarters", "exclusive:raven_mk_vi_r"),
    ),
    _weapon(
        id="kew_9a_dagger",
        name="KEW-9A 'Dagger'",
        ship_class="Strike",
        price=60_000,
        durability=6_000,
        stats={
            "damage_min": 9.0,
            "damage_max": 18.0,
            "armor_piercing": 5.0,
            "range_min": 0.0,
            "range_max": 650.0,
            "optimal_range": 400.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 0.4,
            "power": 2.0,
            "firing_arc": 30.0,
        },
        upgrades=("damage",),
        description="Narrow-arc Raven autocannon optimised for mid-range armor punching.",
        tags=("midrange", "exclusive:raven_mk_vi_r"),
    ),
    _weapon(
        id="kkc_h1_javelin",
        name="KKC-H1 'Javelin'",
        ship_class="Strike",
        price=95_000,
        durability=6_000,
        stats={
            "damage_min": 65.0,
            "damage_max": 100.0,
            "armor_piercing": 35.0,
            "range_min": 100.0,
            "range_max": 1_500.0,
            "optimal_range": 1_000.0,
            "accuracy": 100.0,
            "critical_offense": 150.0,
            "reload": 2.0,
            "power": 6.0,
            "firing_arc": 30.0,
        },
        upgrades=("damage",),
        description="Rhino-exclusive kinetic kill cannon built for long-range armor cracking.",
        tags=("long_range", "exclusive:rhino"),
    ),
    _weapon(
        id="kew_2b_stiletto",
        name="KEW-2B 'Stiletto'",
        ship_class="Strike",
        price=55_000,
        durability=6_000,
        stats={
            "damage_min": 5.0,
            "damage_max": 10.0,
            "armor_piercing": 2.5,
            "range_min": 0.0,
            "range_max": 500.0,
            "optimal_range": 300.0,
            "accuracy": 400.0,
            "critical_offense": 90.0,
            "reload": 0.2,
            "power": 1.4,
            "firing_arc": 40.0,
        },
        upgrades=("damage",),
        description="Rapid Raven machine gun focused on relentless close-range pressure.",
        tags=("close_quarters", "exclusive:raven_mk_vi_r"),
    ),
    _weapon(
        id="mec_a6p",
        name="MEC-A6P 'Fang-P'",
        ship_class="Strike",
        price=10_000,
        durability=6_000,
        stats={
            "damage_min": 1.0,
            "damage_max": 10.0,
            "armor_piercing": 5.0,
            "range_min": 0.0,
            "range_max": 750.0,
            "optimal_range": 300.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 0.5,
            "power": 1.0,
            "firing_arc": 75.0,
        },
        upgrades=("damage", "critical_offense"),
        description="Precision Fang variant tuned for crit-stacking builds.",
        tags=("precision", "rapid_fire"),
    ),
    _weapon(
        id="mec_a8",
        name="MEC-A8 'Tornado'",
        ship_class="Strike",
        price=10_000,
        durability=6_000,
        stats={
            "damage_min": 1.0,
            "damage_max": 10.0,
            "armor_piercing": 5.0,
            "range_min": 0.0,
            "range_max": 600.0,
            "optimal_range": 250.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 0.4,
            "power": 1.0,
            "firing_arc": 75.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Short-range autocannon trading reach for higher cadence.",
        tags=("rapid_fire", "close_quarters"),
    ),
    _weapon(
        id="mec_a8p",
        name="MEC-A8P 'Tornado-P'",
        ship_class="Strike",
        price=10_000,
        durability=6_000,
        stats={
            "damage_min": 1.0,
            "damage_max": 10.0,
            "armor_piercing": 5.0,
            "range_min": 0.0,
            "range_max": 600.0,
            "optimal_range": 250.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 0.4,
            "power": 1.0,
            "firing_arc": 75.0,
        },
        upgrades=("damage", "critical_offense"),
        description="Crit-oriented Tornado preserving the rapid-fire identity.",
        tags=("precision", "rapid_fire"),
    ),
    _weapon(
        id="mec_a9",
        name="MEC-A9 'Hawk'",
        ship_class="Strike",
        price=10_000,
        durability=6_000,
        stats={
            "damage_min": 1.0,
            "damage_max": 10.0,
            "armor_piercing": 5.0,
            "range_min": 0.0,
            "range_max": 900.0,
            "optimal_range": 350.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 0.6,
            "power": 1.0,
            "firing_arc": 75.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Longer-range autocannon tuned for standoff Strike play.",
        tags=("long_range", "skirmisher"),
    ),
    _weapon(
        id="mec_a9p",
        name="MEC-A9P 'Hawk-P'",
        ship_class="Strike",
        price=10_000,
        durability=6_000,
        stats={
            "damage_min": 1.0,
            "damage_max": 10.0,
            "armor_piercing": 5.0,
            "range_min": 0.0,
            "range_max": 900.0,
            "optimal_range": 350.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 0.6,
            "power": 1.0,
            "firing_arc": 75.0,
        },
        upgrades=("damage", "critical_offense"),
        description="Precision Hawk variant rewarding deliberate long-range fire.",
        tags=("precision", "long_range"),
    ),
    _weapon(
        id="gopher_light_mining_cannon",
        name="'Gopher' Light Mining Cannon",
        ship_class="Strike",
        price=5_000,
        durability=6_000,
        stats={
            "damage_min": 1.0,
            "damage_max": 4.0,
            "armor_piercing": 5.0,
            "range_min": 0.0,
            "range_max": 600.0,
            "optimal_range": 250.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 0.5,
            "power": 2.0,
            "firing_arc": 75.0,
            "mining_yield": 5.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Dual-role mining cannon applying a strong asteroid yield multiplier.",
        tags=("mining", "support"),
    ),
    _weapon(
        id="dfsr_18_hornet",
        name="DFSR-18 'Hornet'",
        ship_class="Strike",
        price=52_000,
        durability=6_000,
        stats={
            "damage_min": 200.0,
            "damage_max": 200.0,
            "armor_piercing": 20.0,
            "critical_offense": 100.0,
            "projectile_speed": 210.0,
            "reload": 4.0,
            "power": 16.2,
            "firing_arc": 75.0,
        },
        upgrades=("reload", "power"),
        description="Raven-exclusive unguided rocket pack for sudden burst volleys.",
        tags=("rocket", "exclusive:raven_mk_vi_r"),
    ),
    _weapon(
        id="hd_70p_lightning_p",
        name="HD-70P 'Lightning-P'",
        ship_class="Strike",
        price=10_000,
        durability=6_000,
        stats={
            "damage_min": 25.0,
            "damage_max": 50.0,
            "armor_piercing": 15.0,
            "range_min": 200.0,
            "range_max": 1_000.0,
            "optimal_range": 200.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 10.0,
            "power": 20.0,
            "firing_arc": 75.0,
            "turn_speed": 100.0,
            "projectile_speed": 120.0,
        },
        upgrades=("critical_offense", "reload", "power"),
        description="Precision light missile launcher emphasising crit spikes and cadence.",
        tags=("missile", "precision"),
    ),
    _weapon(
        id="asm_a9_zephyr",
        name="ASM-A9 'Zephyr'",
        ship_class="Strike",
        price=95_000,
        durability=6_000,
        stats={
            "damage_min": 750.0,
            "damage_max": 750.0,
            "armor_piercing": 35.0,
            "range_min": 500.0,
            "range_max": 1_200.0,
            "optimal_range": 750.0,
            "accuracy": 400.0,
            "critical_offense": 0.0,
            "reload": 60.0,
            "power": 5.0,
            "firing_arc": 75.0,
            "turn_speed": 15.0,
            "projectile_speed": 120.0,
        },
        upgrades=("reload",),
        description="Raven-exclusive heavy missile delivering a single massive strike.",
        tags=("heavy_missile", "exclusive:raven_mk_vi_r"),
    ),
    _weapon(
        id="hd_70_lightning",
        name="HD-70 'Lightning'",
        ship_class="Strike",
        price=10_000,
        durability=6_000,
        stats={
            "damage_min": 25.0,
            "damage_max": 50.0,
            "armor_piercing": 15.0,
            "range_min": 200.0,
            "range_max": 1_000.0,
            "optimal_range": 200.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 10.0,
            "power": 20.0,
            "firing_arc": 75.0,
            "turn_speed": 100.0,
            "projectile_speed": 120.0,
        },
        upgrades=("range_max", "reload", "power"),
        description="Baseline Strike missile pod balancing reach and firing cadence.",
        tags=("missile", "generalist"),
    ),
    _weapon(
        id="siw_9m_wasp",
        name="SIW-9M 'Wasp'",
        ship_class="Strike",
        price=75_000,
        durability=6_000,
        stats={
            "damage_min": 300.0,
            "damage_max": 300.0,
            "armor_piercing": 15.0,
            "range_min": 300.0,
            "range_max": 1_000.0,
            "optimal_range": 650.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 30.0,
            "power": 5.0,
            "firing_arc": 75.0,
            "turn_speed": 65.0,
            "projectile_speed": 150.0,
        },
        upgrades=("reload",),
        description="Raven-exclusive interceptor missile tuned for anti-Strike roles.",
        tags=("missile", "exclusive:raven_mk_vi_r"),
    ),
    _weapon(
        id="hd_82_longbow",
        name="HD-82 'Longbow'",
        ship_class="Strike",
        price=10_000,
        durability=6_000,
        stats={
            "damage_min": 25.0,
            "damage_max": 50.0,
            "armor_piercing": 15.0,
            "range_min": 200.0,
            "range_max": 1_250.0,
            "optimal_range": 200.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 12.0,
            "power": 20.0,
            "firing_arc": 75.0,
            "turn_speed": 100.0,
            "projectile_speed": 120.0,
        },
        upgrades=("range_max", "reload", "power"),
        description="Extended-range missile pod designed for persistent kiting.",
        tags=("missile", "long_range"),
    ),
    _weapon(
        id="hd_82p_longbow_p",
        name="HD-82P 'Longbow-P'",
        ship_class="Strike",
        price=10_000,
        durability=6_000,
        stats={
            "damage_min": 25.0,
            "damage_max": 50.0,
            "armor_piercing": 15.0,
            "range_min": 200.0,
            "range_max": 1_250.0,
            "optimal_range": 200.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 12.0,
            "power": 20.0,
            "firing_arc": 75.0,
            "turn_speed": 100.0,
            "projectile_speed": 120.0,
        },
        upgrades=("critical_offense", "reload", "power"),
        description="Precision Longbow variant combining crit spikes with standoff reach.",
        tags=("missile", "precision"),
    ),
    _weapon(
        id="asm_a3_cyclops",
        name="ASM-A3 'Cyclops'",
        ship_class="Strike",
        price=45_000,
        durability=6_000,
        stats={
            "damage_min": 250.0,
            "damage_max": 500.0,
            "armor_piercing": 35.0,
            "range_min": 600.0,
            "range_max": 1_080.0,
            "optimal_range": 840.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 120.0,
            "power": 45.0,
            "firing_arc": 75.0,
            "turn_speed": 70.0,
            "projectile_speed": 85.0,
            "explosion_radius": 400.0,
            "power_damage_min": 40.0,
            "power_damage_max": 60.0,
        },
        upgrades=("power_damage", "range_max", "reload", "power"),
        description="Nuclear torpedo delivering heavy hull and grid damage in a wide blast.",
        tags=("torpedo", "nuclear"),
    ),
    _weapon(
        id="ast_7a_manticore",
        name="AST-7A 'Manticore'",
        ship_class="Strike",
        price=45_000,
        durability=6_000,
        stats={
            "damage_min": 600.0,
            "damage_max": 850.0,
            "armor_piercing": 35.0,
            "range_min": 200.0,
            "range_max": 680.0,
            "optimal_range": 440.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 160.0,
            "power": 70.0,
            "firing_arc": 75.0,
            "turn_speed": 2.0,
            "projectile_speed": 60.0,
            "explosion_radius": 200.0,
            "power_damage_min": 80.0,
            "power_damage_max": 120.0,
        },
        upgrades=("power_damage", "range_max", "reload", "power"),
        description="Tactical nuke favouring point-blank strikes for overwhelming impact.",
        tags=("torpedo", "nuclear"),
    ),
    _weapon(
        id="hd_96_nova",
        name="HD-96 'Nova'",
        ship_class="Strike",
        price=10_000,
        durability=6_000,
        stats={
            "damage_min": 125.0,
            "damage_max": 250.0,
            "armor_piercing": 40.0,
            "range_min": 200.0,
            "range_max": 680.0,
            "optimal_range": 440.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 20.0,
            "power": 30.0,
            "firing_arc": 75.0,
            "turn_speed": 2.0,
            "projectile_speed": 80.0,
        },
        upgrades=("range_max", "reload", "power"),
        description="High-powered short-range missile emphasising armor-piercing strikes.",
        tags=("missile", "breacher"),
    ),
    # Strike-class hull modules -------------------------------------------
    _module(
        id="strike_composite_plating",
        name="Strike Composite Plating",
        slot_family="hull",
        ship_class="Strike",
        price=8_000,
        durability=6_000,
        stats={
            "armor": 2.25,
            "hull_hp": 22.5,
            "acceleration": -0.3,
            "turn_accel": -0.75,
        },
        upgrades=("armor", "hull_hp"),
        description="Balanced plating adding both armor and hull with minor inertia hits.",
        tags=("balanced", "survivability"),
    ),
    _module(
        id="strike_hull_plating",
        name="Strike Hull Plating",
        slot_family="hull",
        ship_class="Strike",
        price=8_000,
        durability=6_000,
        stats={
            "hull_hp": 45.0,
            "acceleration": -0.2,
            "turn_accel": -1.0,
        },
        upgrades=("hull_hp",),
        description="Standard hull reinforcement for Strikes with heavier inertia.",
        tags=("survivability", "bulk"),
    ),
    _module(
        id="strike_armor_plating",
        name="Strike Armor Plating",
        slot_family="hull",
        ship_class="Strike",
        price=8_000,
        durability=6_000,
        stats={
            "armor": 4.5,
            "acceleration": -0.4,
            "turn_accel": -0.5,
        },
        upgrades=("armor",),
        description="Armor-focused plating trading acceleration for mitigation.",
        tags=("armor", "survivability"),
    ),
    _module(
        id="strike_ht_plating",
        name="Strike HT Plating",
        slot_family="hull",
        ship_class="Strike",
        price=8_000,
        durability=6_000,
        stats={
            "critical_defense": 7.5,
        },
        upgrades=("critical_defense",),
        description="Critical-defense plating guarding against spike damage.",
        tags=("defensive", "crit_guard"),
    ),
    _module(
        id="strike_ht_hull_plating",
        name="Strike HT Hull Plating",
        slot_family="hull",
        ship_class="Strike",
        price=8_000,
        durability=6_000,
        stats={
            "critical_defense": 2.5,
            "hull_hp": 30.0,
            "acceleration": -0.13,
            "turn_accel": -0.67,
        },
        upgrades=("critical_defense", "hull_hp"),
        description="Heavy-tuned plating mixing hull buffers with crit protection.",
        tags=("survivability", "crit_guard"),
    ),
    _module(
        id="strike_ht_armor_plating",
        name="Strike HT Armor Plating",
        slot_family="hull",
        ship_class="Strike",
        price=8_000,
        durability=6_000,
        stats={
            "armor": 3.0,
            "critical_defense": 2.5,
            "acceleration": -0.27,
            "turn_accel": -0.33,
        },
        upgrades=("armor", "critical_defense"),
        description="Heavy-tuned armor blend enhancing mitigation and crit resilience.",
        tags=("armor", "crit_guard"),
    ),
    _module(
        id="strike_ht_composite_plating",
        name="Strike HT Composite Plating",
        slot_family="hull",
        ship_class="Strike",
        price=8_000,
        durability=6_000,
        stats={
            "armor": 1.8,
            "critical_defense": 1.5,
            "hull_hp": 18.0,
            "acceleration": -0.24,
            "turn_accel": -0.6,
        },
        upgrades=("armor", "critical_defense", "hull_hp"),
        description="All-round heavy-tuned composite improving every survivability axis.",
        tags=("balanced", "survivability"),
    ),
    _module(
        id="strike_system_redundancy",
        name="Strike System Redundancy",
        slot_family="hull",
        ship_class="Strike",
        price=5_000,
        durability=6_000,
        stats={
            "hull_recovery": 0.5,
        },
        upgrades=("hull_recovery",),
        description="Passive hull regen package improving out-of-combat recovery.",
        tags=("sustain", "support"),
    ),
    _module(
        id="strike_damage_control",
        name="Strike Damage Control",
        slot_family="hull",
        ship_class="Strike",
        price=8_000,
        durability=6_000,
        stats={
            "hull_restore": 50.0,
            "reload": 30.0,
            "power": 50.0,
        },
        upgrades=("hull_restore",),
        description="Active repair system delivering burst heals on a 30 s cooldown.",
        tags=("active", "support"),
    ),
    # Strike-class engine modules -----------------------------------------
    _module(
        id="light_drive_overcharger",
        name="Light Drive Overcharger",
        slot_family="engine",
        ship_class="Strike",
        price=5_000,
        durability=6_000,
        stats={
            "max_speed": 1.25,
            "boost_speed": 1.25,
        },
        upgrades=("max_speed", "boost_speed"),
        description=(
            "Baseline Strike-class engine upgrade granting flat cruise and boost "
            "speed bonuses for better mobility without affecting handling."
        ),
        tags=("speed", "cruise"),
    ),
    _module(
        id="light_turbo_boosters",
        name="Light Turbo Boosters",
        slot_family="engine",
        ship_class="Strike",
        price=5_000,
        durability=6_000,
        stats={
            "acceleration": 1.0,
            "boost_speed": 2.5,
        },
        upgrades=("acceleration", "boost_speed"),
        description=(
            "Strike-class engine module boosting acceleration and boost speed, "
            "ideal for hit-and-run bursts and quick disengages."
        ),
        tags=("acceleration", "boost"),
    ),
    _module(
        id="light_gyro_stabilization",
        name="Light Gyro-Stabilization",
        slot_family="engine",
        ship_class="Strike",
        price=5_000,
        durability=6_000,
        stats={
            "turn_rate": 2.5,
            "turn_accel": 2.5,
        },
        upgrades=("turn_rate", "turn_accel"),
        description=(
            "Strike maneuvering gyro that raises turn speed and turn acceleration "
            "to sharpen agility in close engagements."
        ),
        tags=("maneuvering",),
    ),
    _module(
        id="light_rcs_ducting",
        name="Light RCS Ducting",
        slot_family="engine",
        ship_class="Strike",
        price=5_000,
        durability=6_000,
        stats={
            "avoidance_rating": 15.0,
        },
        upgrades=("avoidance_rating",),
        description=(
            "Strike RCS ducting focused on avoidance so the ship shrugs off "
            "direct-fire attacks without changing its speed profile."
        ),
        tags=("defensive", "agility"),
    ),
    _module(
        id="t8_drive_turbo_charger",
        name="T8 Drive Turbo Charger",
        slot_family="engine",
        ship_class="Strike",
        price=60_000,
        durability=6_000,
        stats={
            "max_speed_percent": 3.0,
            "boost_speed_percent": 4.0,
        },
        upgrades=("max_speed_percent", "boost_speed_percent"),
        description=(
            "Raven Mk VI-R exclusive turbo charger increasing base and boost "
            "speeds by percentage for markedly quicker flanking runs."
        ),
        tags=("speed", "exclusive:raven_mk_vi_r"),
    ),
    _module(
        id="fog_gyro_stabilization",
        name="FoG Gyro-Stabilization System",
        slot_family="engine",
        ship_class="Strike",
        price=50_000,
        durability=6_000,
        stats={
            "turn_rate_percent": 10.0,
            "turn_accel_percent": 10.0,
        },
        upgrades=("turn_rate_percent", "turn_accel_percent"),
        description=(
            "Advanced Raven gyro system multiplying turn speed and turn "
            "acceleration for razor-sharp tracking."
        ),
        tags=("maneuvering", "exclusive:raven_mk_vi_r"),
    ),
    _module(
        id="translation_rcs_thrusters",
        name="Translation RCS Thrusters",
        slot_family="engine",
        ship_class="Strike",
        price=50_000,
        durability=6_000,
        stats={
            "turn_rate_percent": 10.0,
            "strafe_speed_percent": 15.0,
        },
        upgrades=("turn_rate_percent", "strafe_speed_percent"),
        description=(
            "Specialized Raven RCS thrusters boosting turn rate and lateral "
            "strafe capability for aggressive maneuvering."
        ),
        tags=("maneuvering", "exclusive:raven_mk_vi_r"),
    ),
    _module(
        id="t15_pulsed_plasma_thruster",
        name="T15 Pulsed Plasma Thruster",
        slot_family="engine",
        ship_class="Strike",
        price=90_000,
        durability=6_000,
        stats={
            "boost_speed_percent": 6.0,
            "acceleration_percent": 20.0,
            "boost_cost_percent": 25.0,
        },
        upgrades=("boost_speed_percent", "acceleration_percent"),
        description=(
            "High-end Raven booster trading efficiency for substantially higher "
            "acceleration and boost speed."
        ),
        tags=("boost", "exclusive:raven_mk_vi_r"),
    ),
    _module(
        id="coupled_rcs_ducting",
        name="Coupled RCS Ducting",
        slot_family="engine",
        ship_class="Strike",
        price=62_000,
        durability=6_000,
        stats={
            "avoidance_percent": 4.0,
            "boost_speed_percent": -2.5,
        },
        upgrades=("avoidance_percent",),
        description=(
            "Raven defensive RCS package raising avoidance at the cost of raw "
            "boost speed, suiting evasive builds."
        ),
        tags=("defensive", "exclusive:raven_mk_vi_r"),
    ),
    _module(
        id="fbs_12_engine_overload",
        name="FBS-12 Engine Overload System",
        slot_family="engine",
        ship_class="Strike",
        price=60_000,
        durability=6_000,
        stats={
            "boost_speed_active": 16.0,
            "boost_acceleration_multiplier": 3.0,
            "boost_cost_percent": 200.0,
            "duration": 8.0,
            "reload": 80.0,
            "power": 60.0,
        },
        upgrades=("duration",),
        description=(
            "Rhino-exclusive active overdrive that floods the engines for a short "
            "boost surge while greatly increasing energy cost."
        ),
        tags=("active", "exclusive:rhino"),
    ),
    # Escort-class hull modules -------------------------------------------
    _module(
        id="escort_composite_plating",
        name="Escort Composite Plating",
        slot_family="hull",
        ship_class="Escort",
        price=12_000,
        durability=18_000,
        stats={
            "armor": 2.13,
            "hull_hp": 82.5,
            "acceleration": -0.15,
            "turn_accel": -0.38,
        },
        upgrades=("armor", "hull_hp"),
        description=(
            "Balanced Escort plating that blends armor and hull buffers at the "
            "cost of moderate handling penalties."
        ),
        tags=("balanced", "survivability"),
    ),
    _module(
        id="escort_hull_plating",
        name="Escort Hull Plating",
        slot_family="hull",
        ship_class="Escort",
        price=12_000,
        durability=18_000,
        stats={
            "hull_hp": 165.0,
            "acceleration": -0.1,
            "turn_accel": -0.5,
        },
        upgrades=("hull_hp",),
        description="Baseline Escort hull reinforcement providing a large HP buffer.",
        tags=("survivability", "bulk"),
    ),
    _module(
        id="escort_armor_plating",
        name="Escort Armor Plating",
        slot_family="hull",
        ship_class="Escort",
        price=12_000,
        durability=18_000,
        stats={
            "armor": 4.25,
            "acceleration": -0.2,
            "turn_accel": -0.25,
        },
        upgrades=("armor",),
        description="Armor-focused Escort plating trading agility for mitigation.",
        tags=("armor", "survivability"),
    ),
    _module(
        id="escort_ht_plating",
        name="Escort HT Plating",
        slot_family="hull",
        ship_class="Escort",
        price=12_000,
        durability=18_000,
        stats={
            "critical_defense": 7.5,
        },
        upgrades=("critical_defense",),
        description="Heavy-tuned plating bolstering crit resistance without inertia hits.",
        tags=("defensive", "crit_guard"),
    ),
    _module(
        id="escort_ht_hull_plating",
        name="Escort HT Hull Plating",
        slot_family="hull",
        ship_class="Escort",
        price=12_000,
        durability=18_000,
        stats={
            "critical_defense": 2.5,
            "hull_hp": 110.0,
            "acceleration": -0.07,
            "turn_accel": -0.33,
        },
        upgrades=("critical_defense", "hull_hp"),
        description="Heavy-tuned hybrid plating mixing hull buffers with crit protection.",
        tags=("survivability", "crit_guard"),
    ),
    _module(
        id="escort_ht_armor_plating",
        name="Escort HT Armor Plating",
        slot_family="hull",
        ship_class="Escort",
        price=12_000,
        durability=18_000,
        stats={
            "armor": 2.83,
            "critical_defense": 2.5,
            "acceleration": -0.13,
            "turn_accel": -0.17,
        },
        upgrades=("armor", "critical_defense"),
        description="Heavy-tuned armor blend raising mitigation and crit resilience.",
        tags=("armor", "crit_guard"),
    ),
    _module(
        id="escort_ht_composite_plating",
        name="Escort HT Composite Plating",
        slot_family="hull",
        ship_class="Escort",
        price=12_000,
        durability=18_000,
        stats={
            "armor": 1.7,
            "critical_defense": 1.5,
            "hull_hp": 66.0,
            "acceleration": -0.12,
            "turn_accel": -0.3,
        },
        upgrades=("armor", "critical_defense", "hull_hp"),
        description="Balanced heavy-tuned plating covering every defensive axis.",
        tags=("balanced", "crit_guard"),
    ),
    _module(
        id="escort_system_redundancy",
        name="Escort System Redundancy",
        slot_family="hull",
        ship_class="Escort",
        price=7_500,
        durability=18_000,
        stats={
            "hull_recovery": 1.5,
        },
        upgrades=("hull_recovery",),
        description="Passive Escort regen package improving sustained hull recovery.",
        tags=("sustain", "support"),
    ),
    _module(
        id="escort_damage_control",
        name="Escort Damage Control",
        slot_family="hull",
        ship_class="Escort",
        price=12_000,
        durability=18_000,
        stats={
            "hull_restore": 150.0,
            "reload": 30.0,
            "power": 100.0,
        },
        upgrades=("hull_restore",),
        description="Active Escort repair module restoring hull on a 30 s cooldown.",
        tags=("active", "support"),
    ),
    # Escort-class weapons -------------------------------------------------
    _weapon(
        id="mec_e12",
        name="MEC-E12 'Claw'",
        ship_class="Escort",
        price=15_000,
        durability=18_000,
        stats={
            "damage_min": 10.0,
            "damage_max": 25.0,
            "armor_piercing": 15.0,
            "range_min": 0.0,
            "range_max": 1_150.0,
            "optimal_range": 450.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 1.5,
            "power": 6.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Balanced Escort medium cannon for standard single-target fire control.",
        tags=("balanced", "medium_cannon", "standard_targeting"),
    ),
    _weapon(
        id="mec_e12m",
        name="MEC-E12(M) 'Claw'",
        ship_class="Escort",
        price=15_000,
        durability=18_000,
        stats={
            "damage_min": 10.0,
            "damage_max": 25.0,
            "armor_piercing": 15.0,
            "range_min": 0.0,
            "range_max": 1_150.0,
            "optimal_range": 450.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 1.5,
            "power": 6.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Multi-targeting Claw battery that spreads volleys across several locked targets.",
        tags=("balanced", "medium_cannon", "multi_target"),
    ),
    _weapon(
        id="mec_e12p",
        name="MEC-E12P 'Claw-P'",
        ship_class="Escort",
        price=15_000,
        durability=18_000,
        stats={
            "damage_min": 10.0,
            "damage_max": 25.0,
            "armor_piercing": 15.0,
            "range_min": 0.0,
            "range_max": 1_150.0,
            "optimal_range": 450.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 1.5,
            "power": 6.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "optimal_range", "critical_offense"),
        description="Precision Claw variant with enhanced crit potential and multi-targeting logic.",
        tags=("balanced", "medium_cannon", "multi_target", "precision"),
    ),
    _weapon(
        id="mec_e13",
        name="MEC-E13 'Hurricane'",
        ship_class="Escort",
        price=15_000,
        durability=18_000,
        stats={
            "damage_min": 10.0,
            "damage_max": 25.0,
            "armor_piercing": 15.0,
            "range_min": 0.0,
            "range_max": 900.0,
            "optimal_range": 350.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 1.2,
            "power": 6.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Rapid-fire Hurricane cannon tuned for close-range single-target pressure.",
        tags=("rapid_fire", "medium_cannon", "standard_targeting"),
    ),
    _weapon(
        id="mec_e13m",
        name="MEC-E13(M) 'Hurricane'",
        ship_class="Escort",
        price=15_000,
        durability=18_000,
        stats={
            "damage_min": 10.0,
            "damage_max": 25.0,
            "armor_piercing": 15.0,
            "range_min": 0.0,
            "range_max": 900.0,
            "optimal_range": 350.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 1.2,
            "power": 6.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Multi-target Hurricane battery that splits salvos across nearby threats.",
        tags=("rapid_fire", "medium_cannon", "multi_target"),
    ),
    _weapon(
        id="mec_e13p",
        name="MEC-E13P 'Hurricane-P'",
        ship_class="Escort",
        price=15_000,
        durability=18_000,
        stats={
            "damage_min": 10.0,
            "damage_max": 25.0,
            "armor_piercing": 15.0,
            "range_min": 0.0,
            "range_max": 900.0,
            "optimal_range": 350.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 1.2,
            "power": 6.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "optimal_range", "critical_offense"),
        description="Precision Hurricane variant delivering crit-focused multi-target barrages.",
        tags=("rapid_fire", "medium_cannon", "multi_target", "precision"),
    ),
    _weapon(
        id="mec_e17",
        name="MEC-E17 'Falcon'",
        ship_class="Escort",
        price=15_000,
        durability=18_000,
        stats={
            "damage_min": 10.0,
            "damage_max": 25.0,
            "armor_piercing": 15.0,
            "range_min": 0.0,
            "range_max": 1_350.0,
            "optimal_range": 550.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 1.8,
            "power": 6.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Long-range Falcon cannon for Escorts relying on single-target fire support.",
        tags=("precision", "medium_cannon", "standard_targeting"),
    ),
    _weapon(
        id="mec_e17m",
        name="MEC-E17(M) 'Falcon'",
        ship_class="Escort",
        price=15_000,
        durability=18_000,
        stats={
            "damage_min": 10.0,
            "damage_max": 25.0,
            "armor_piercing": 15.0,
            "range_min": 0.0,
            "range_max": 1_350.0,
            "optimal_range": 550.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 1.8,
            "power": 6.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Multi-target Falcon battery allowing distributed long-range salvos.",
        tags=("precision", "medium_cannon", "multi_target"),
    ),
    _weapon(
        id="mec_e17p",
        name="MEC-E17P 'Falcon-P'",
        ship_class="Escort",
        price=15_000,
        durability=18_000,
        stats={
            "damage_min": 10.0,
            "damage_max": 25.0,
            "armor_piercing": 15.0,
            "range_min": 0.0,
            "range_max": 1_350.0,
            "optimal_range": 550.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 1.8,
            "power": 6.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "optimal_range", "critical_offense"),
        description="Precision Falcon variant with heightened crit spikes and multi-targeting.",
        tags=("precision", "medium_cannon", "multi_target"),
    ),
    _weapon(
        id="mole_mining_battery",
        name="'Mole' Medium Mining Battery",
        ship_class="Escort",
        price=7_500,
        durability=18_000,
        stats={
            "damage_min": 4.0,
            "damage_max": 10.0,
            "armor_piercing": 25.0,
            "range_min": 0.0,
            "range_max": 900.0,
            "optimal_range": 350.0,
            "accuracy": 350.0,
            "critical_offense": 100.0,
            "reload": 1.5,
            "power": 12.0,
            "firing_arc": 180.0,
            "mining_yield_multiplier": 5.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Escort mining cannon providing ×5 asteroid yield alongside modest DPS.",
        tags=("mining", "medium_cannon"),
    ),
    _weapon(
        id="hd_m50p",
        name="HD-M50P 'Thunderbolt-P'",
        ship_class="Escort",
        price=15_000,
        durability=18_000,
        stats={
            "damage_min": 40.0,
            "damage_max": 100.0,
            "armor_piercing": 25.0,
            "range_min": 200.0,
            "range_max": 1_350.0,
            "optimal_range": 850.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 12.5,
            "power": 50.0,
            "firing_arc": 180.0,
            "turn_speed": 75.0,
            "projectile_speed": 100.0,
        },
        upgrades=("range_max", "reload", "power", "critical_offense"),
        description="Precision Thunderbolt battery with crit scaling and multi-target missile logic.",
        tags=("missile", "guided", "multi_target", "precision"),
    ),
    _weapon(
        id="hd_m50s",
        name="HD-M50(S) 'Thunderbolt'",
        ship_class="Escort",
        price=15_000,
        durability=18_000,
        stats={
            "damage_min": 40.0,
            "damage_max": 100.0,
            "armor_piercing": 25.0,
            "range_min": 200.0,
            "range_max": 1_350.0,
            "optimal_range": 850.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 12.5,
            "power": 50.0,
            "firing_arc": 180.0,
            "turn_speed": 75.0,
            "projectile_speed": 100.0,
        },
        upgrades=("range_max", "reload", "power"),
        description="Baseline Thunderbolt missile rack offering flexible mid-range firepower.",
        tags=("missile", "guided", "standard_targeting"),
    ),
    _weapon(
        id="hd_m50m",
        name="HD-M50(M) 'Thunderbolt'",
        ship_class="Escort",
        price=15_000,
        durability=18_000,
        stats={
            "damage_min": 40.0,
            "damage_max": 100.0,
            "armor_piercing": 25.0,
            "range_min": 200.0,
            "range_max": 1_350.0,
            "optimal_range": 850.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 12.5,
            "power": 50.0,
            "firing_arc": 180.0,
            "turn_speed": 75.0,
            "projectile_speed": 100.0,
        },
        upgrades=("range_max", "reload", "power"),
        description="Multi-target Thunderbolt rack distributing missiles across multiple locks.",
        tags=("missile", "guided", "multi_target"),
    ),
    _weapon(
        id="hd_m63",
        name="HD-M63 'Scorpio'",
        ship_class="Escort",
        price=15_000,
        durability=18_000,
        stats={
            "damage_min": 40.0,
            "damage_max": 100.0,
            "armor_piercing": 25.0,
            "range_min": 200.0,
            "range_max": 1_600.0,
            "optimal_range": 900.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 15.0,
            "power": 50.0,
            "firing_arc": 180.0,
            "turn_speed": 75.0,
            "projectile_speed": 100.0,
        },
        upgrades=("range_max", "reload", "power"),
        description="Baseline long-range Scorpio missile rack for deliberate, efficient volleys.",
        tags=("missile", "long_range", "standard_targeting"),
    ),
    _weapon(
        id="hd_m63m",
        name="HD-M63(M) 'Scorpio'",
        ship_class="Escort",
        price=15_000,
        durability=18_000,
        stats={
            "damage_min": 40.0,
            "damage_max": 100.0,
            "armor_piercing": 25.0,
            "range_min": 200.0,
            "range_max": 1_600.0,
            "optimal_range": 900.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 15.0,
            "power": 50.0,
            "firing_arc": 180.0,
            "turn_speed": 75.0,
            "projectile_speed": 100.0,
        },
        upgrades=("range_max", "reload", "power"),
        description="Multi-targeting Scorpio launcher sustaining pressure across distant foes.",
        tags=("missile", "long_range", "multi_target"),
    ),
    _weapon(
        id="hd_m63p",
        name="HD-M63P 'Scorpio-P'",
        ship_class="Escort",
        price=15_000,
        durability=18_000,
        stats={
            "damage_min": 40.0,
            "damage_max": 100.0,
            "armor_piercing": 25.0,
            "range_min": 200.0,
            "range_max": 1_600.0,
            "optimal_range": 900.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 15.0,
            "power": 50.0,
            "firing_arc": 180.0,
            "turn_speed": 75.0,
            "projectile_speed": 100.0,
        },
        upgrades=("range_max", "reload", "power", "critical_offense"),
        description="Precision Scorpio variant amplifying crit spikes with multi-target salvos.",
        tags=("missile", "long_range", "multi_target", "precision"),
    ),
    _weapon(
        id="ac_42_blaster",
        name="AC-42 'Blaster'",
        ship_class="Escort",
        price=175_000,
        durability=18_000,
        stats={
            "damage_min": 120.0,
            "damage_max": 155.0,
            "armor_piercing": 60.0,
            "range_min": 500.0,
            "range_max": 2_150.0,
            "optimal_range": 1_450.0,
            "accuracy": 335.0,
            "critical_offense": 200.0,
            "reload": 2.5,
            "power": 9.0,
            "firing_arc": 90.0,
        },
        upgrades=("damage",),
        description="Capital-only cannon letting Escorts threaten the largest hulls head-on.",
        tags=("medium_cannon", "anti_capital"),
    ),
    _weapon(
        id="asm_12_agrius",
        name="ASM-12 'Agrius'",
        ship_class="Escort",
        price=60_000,
        durability=18_000,
        stats={
            "damage_min": 600.0,
            "damage_max": 1_000.0,
            "armor_piercing": 25.0,
            "range_min": 800.0,
            "range_max": 1_600.0,
            "optimal_range": 1_200.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 240.0,
            "power": 70.0,
            "firing_arc": 180.0,
            "turn_speed": 70.0,
            "projectile_speed": 85.0,
            "explosion_radius": 400.0,
            "power_damage_min": 40.0,
            "power_damage_max": 60.0,
        },
        upgrades=("power_damage", "range_max", "reload", "power"),
        description="Escort-class nuclear torpedo delivering devastating hull and power damage.",
        tags=("torpedo", "nuclear"),
    ),
    # Line-class weapons ---------------------------------------------------
    _weapon(
        id="mec_l31",
        name="MEC-L31 'Talon'",
        ship_class="Line",
        price=20_000,
        durability=17_500,
        stats={
            "damage_min": 35.0,
            "damage_max": 70.0,
            "armor_piercing": 35.0,
            "range_min": 0.0,
            "range_max": 1_700.0,
            "optimal_range": 675.0,
            "accuracy": 125.0,
            "critical_offense": 100.0,
            "reload": 4.0,
            "power": 25.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Baseline heavy cannon battery for sustained line combat.",
        tags=("heavy_cannon", "mid_range"),
    ),
    _weapon(
        id="mec_l34",
        name="MEC-L34 'Cyclone'",
        ship_class="Line",
        price=20_000,
        durability=17_500,
        stats={
            "damage_min": 35.0,
            "damage_max": 70.0,
            "armor_piercing": 35.0,
            "range_min": 0.0,
            "range_max": 1_350.0,
            "optimal_range": 550.0,
            "accuracy": 125.0,
            "critical_offense": 100.0,
            "reload": 3.2,
            "power": 25.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Faster-cycling heavy cannon ideal for brawling ranges.",
        tags=("heavy_cannon", "close_quarters"),
    ),
    _weapon(
        id="mec_l35",
        name="MEC-L35 'Eagle'",
        ship_class="Line",
        price=20_000,
        durability=17_500,
        stats={
            "damage_min": 35.0,
            "damage_max": 70.0,
            "armor_piercing": 35.0,
            "range_min": 0.0,
            "range_max": 2_000.0,
            "optimal_range": 800.0,
            "accuracy": 125.0,
            "critical_offense": 100.0,
            "reload": 4.8,
            "power": 25.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Long-range heavy cannon that trades rate of fire for reach.",
        tags=("heavy_cannon", "long_range"),
    ),
    _weapon(
        id="hd_h40",
        name="HD-H40 'Stormstrike'",
        ship_class="Line",
        price=20_000,
        durability=17_500,
        stats={
            "damage_min": 55.0,
            "damage_max": 150.0,
            "armor_piercing": 35.0,
            "range_min": 200.0,
            "range_max": 1_800.0,
            "optimal_range": 1_000.0,
            "accuracy": 125.0,
            "critical_offense": 100.0,
            "reload": 15.0,
            "power": 100.0,
            "firing_arc": 180.0,
            "turn_speed": 30.0,
            "projectile_speed": 80.0,
        },
        upgrades=("damage", "range_max"),
        description="Guided heavy missile battery delivering punishing alpha.",
        tags=("missile", "heavy"),
    ),
    _weapon(
        id="mec_l39f",
        name="MEC-L39F 'Landslide'",
        ship_class="Line",
        price=20_000,
        durability=17_500,
        stats={
            "damage_min": 1.0,
            "damage_max": 35.0,
            "armor_piercing": 15.0,
            "range_min": 500.0,
            "range_max": 800.0,
            "optimal_range": 800.0,
            "accuracy": 300.0,
            "critical_offense": 100.0,
            "reload": 1.0,
            "power": 7.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "range_max", "optimal_range"),
        description="Area flak battery for anti-missile and strike suppression.",
        tags=("flak", "defensive"),
    ),
    _weapon(
        id="mec_l30p",
        name="MEC-L30P 'Brushfire'",
        ship_class="Line",
        price=20_000,
        durability=17_500,
        stats={
            "damage_min": 1.0,
            "damage_max": 5.0,
            "armor_piercing": 5.0,
            "range_min": 0.0,
            "range_max": 540.0,
            "optimal_range": 400.0,
            "accuracy": 500.0,
            "critical_offense": 100.0,
            "reload": 0.5,
            "power": 3.5,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "range_max", "optimal_range"),
        description="Close-in defense battery focused on missile interception.",
        tags=("point_defense", "ciws"),
    ),
    _weapon(
        id="hd_h48",
        name="HD-H48 'Ballista'",
        ship_class="Line",
        price=20_000,
        durability=17_500,
        stats={
            "damage_min": 55.0,
            "damage_max": 150.0,
            "armor_piercing": 35.0,
            "range_min": 200.0,
            "range_max": 2_000.0,
            "optimal_range": 1_200.0,
            "accuracy": 125.0,
            "critical_offense": 100.0,
            "reload": 18.0,
            "power": 100.0,
            "firing_arc": 180.0,
            "turn_speed": 30.0,
            "projectile_speed": 80.0,
        },
        upgrades=("damage", "range_max"),
        description="Extended-range heavy missile battery for bombardment.",
        tags=("missile", "long_range"),
    ),
    # Line-class hull modules -------------------------------------------
    _module(
        id="line_hull_plating",
        name="Line Hull Plating",
        slot_family="hull",
        ship_class="Line",
        price=16_000,
        durability=42_000,
        stats={
            "hull_hp": 350.0,
            "acceleration": -0.05,
            "turn_accel": -0.2,
        },
        upgrades=("hull_hp",),
        description="Baseline hull reinforcement boosting durability with light inertia penalties.",
        tags=("survivability", "bulk"),
    ),
    _module(
        id="line_armor_plating",
        name="Line Armor Plating",
        slot_family="hull",
        ship_class="Line",
        price=16_000,
        durability=42_000,
        stats={
            "armor": 3.5,
            "acceleration": -0.1,
            "turn_accel": -0.1,
        },
        upgrades=("armor",),
        description="Armor-centric plating trading agility for heavier mitigation.",
        tags=("armor", "survivability"),
    ),
    _module(
        id="line_ht_plating",
        name="Line HT Plating",
        slot_family="hull",
        ship_class="Line",
        price=16_000,
        durability=42_000,
        stats={
            "critical_defense": 7.5,
        },
        upgrades=("critical_defense",),
        description="Heavy-tuned plating focused on critical hit protection.",
        tags=("defensive", "crit_guard"),
    ),
    _module(
        id="line_composite_plating",
        name="Line Composite Plating",
        slot_family="hull",
        ship_class="Line",
        price=16_000,
        durability=42_000,
        stats={
            "armor": 1.75,
            "hull_hp": 175.0,
            "acceleration": -0.08,
            "turn_accel": -0.15,
        },
        upgrades=("armor", "hull_hp"),
        description="Balanced composite plating adding both armor and hull capacity.",
        tags=("balanced", "survivability"),
    ),
    _module(
        id="line_ht_hull_plating",
        name="Line HT Hull Plating",
        slot_family="hull",
        ship_class="Line",
        price=16_000,
        durability=42_000,
        stats={
            "critical_defense": 2.5,
            "hull_hp": 233.33333333333334,
            "acceleration": -0.03,
            "turn_accel": -0.13,
        },
        upgrades=("critical_defense", "hull_hp"),
        description="Heavy-tuned reinforcement blending hull buffer and crit resistance.",
        tags=("survivability", "crit_guard"),
    ),
    _module(
        id="line_ht_armor_plating",
        name="Line HT Armor Plating",
        slot_family="hull",
        ship_class="Line",
        price=16_000,
        durability=42_000,
        stats={
            "armor": 2.3333333333333335,
            "critical_defense": 2.5,
            "acceleration": -0.07,
            "turn_accel": -0.07,
        },
        upgrades=("armor", "critical_defense"),
        description="Heavy-tuned armor layering improving mitigation and crit shielding.",
        tags=("armor", "crit_guard"),
    ),
    _module(
        id="line_ht_composite_plating",
        name="Line HT Composite Plating",
        slot_family="hull",
        ship_class="Line",
        price=16_000,
        durability=42_000,
        stats={
            "armor": 1.4,
            "critical_defense": 1.5,
            "hull_hp": 140.0,
            "acceleration": -0.05,
            "turn_accel": -0.1,
        },
        upgrades=("armor", "critical_defense", "hull_hp"),
        description="Heavy-tuned composite covering every defensive axis with manageable penalties.",
        tags=("balanced", "survivability"),
    ),
    # Capital-class weapons -----------------------------------------------
    _weapon(
        id="hag_mk16a",
        name="HAG-MK16A 'Gram'",
        ship_class="Capital",
        price=500_000,
        durability=20_000,
        stats={
            "damage_min": 75.0,
            "damage_max": 135.0,
            "armor_piercing": 35.0,
            "range_min": 2_300.0,
            "range_max": 4_000.0,
            "optimal_range": 2_750.0,
            "accuracy": 125.0,
            "critical_offense": 100.0,
            "reload": 8.0,
            "power": 64.0,
            "firing_arc": 35.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Siege artillery cannon built for devastating broadsides.",
        tags=("artillery", "siege"),
    ),
    _weapon(
        id="pol_x01",
        name="POL-X01 'Plasma Orb Launcher'",
        ship_class="Capital",
        price=0,
        durability=18_000,
        stats={
            "damage_min": 1_000.0,
            "damage_max": 2_200.0,
            "armor_piercing": 90.0,
            "range_min": 2_500.0,
            "range_max": 4_000.0,
            "optimal_range": 3_250.0,
            "accuracy": 110.0,
            "critical_offense": 120.0,
            "reload": 60.0,
            "power": 1_150.0,
            "firing_arc": 5.0,
        },
        upgrades=("damage", "reload"),
        description="Thorim-exclusive spinal plasma weapon that consumes full reserves to launch a massive orb. Cannot engage Strike-class ships and will not fire inside 2.5 km.",
        tags=("spinal", "exclusive:thorim_siege", "requires_full_power"),
    ),
    _weapon(
        id="pd_x30p",
        name="PD-X30P 'Wildfire'",
        ship_class="Capital",
        price=300_000,
        durability=25_000,
        stats={
            "damage_min": 3.0,
            "damage_max": 7.0,
            "armor_piercing": 5.0,
            "range_min": 0.0,
            "range_max": 1_200.0,
            "optimal_range": 500.0,
            "accuracy": 500.0,
            "critical_offense": 100.0,
            "reload": 0.5,
            "power": 3.5,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "range"),
        description="Capital CIWS battery for layered close-in defence.",
        tags=("point_defense", "ciws"),
    ),
    _weapon(
        id="m_37a",
        name="M-37A 'Fusillade'",
        ship_class="Capital",
        price=450_000,
        durability=25_000,
        stats={
            "damage_min": 20.0,
            "damage_max": 30.0,
            "armor_piercing": 15.0,
            "range_min": 1_000.0,
            "range_max": 1_400.0,
            "optimal_range": 1_200.0,
            "accuracy": 300.0,
            "critical_offense": 100.0,
            "reload": 1.0,
            "power": 5.0,
            "firing_arc": 45.0,
        },
        upgrades=("damage", "range"),
        description="Spot flak turret covering narrow arcs with concentrated bursts.",
        tags=("flak", "defensive"),
    ),
    _weapon(
        id="m_39f",
        name="M-39F 'Avalanche'",
        ship_class="Capital",
        price=350_000,
        durability=20_000,
        stats={
            "damage_min": 10.0,
            "damage_max": 28.0,
            "armor_piercing": 15.0,
            "range_min": 900.0,
            "range_max": 1_500.0,
            "optimal_range": 1_200.0,
            "accuracy": 300.0,
            "critical_offense": 100.0,
            "reload": 1.0,
            "power": 7.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "range"),
        description="Wide-arc flak battery saturating approach vectors with bursts.",
        tags=("flak", "defensive"),
    ),
    _weapon(
        id="ram_179a",
        name="RAM-179A 'Stormstrike'",
        ship_class="Capital",
        price=280_000,
        durability=25_000,
        stats={
            "damage_min": 250.0,
            "damage_max": 250.0,
            "armor_piercing": 35.0,
            "range_min": 0.0,
            "range_max": 1_800.0,
            "optimal_range": 1_100.0,
            "accuracy": 125.0,
            "critical_offense": 100.0,
            "reload": 20.0,
            "power": 80.0,
            "firing_arc": 360.0,
            "turn_speed": 45.0,
            "projectile_speed": 95.0,
        },
        upgrades=("damage", "range"),
        description="360° guided missile rack for heavy anti-ship salvos.",
        tags=("missile", "guided"),
    ),
    _weapon(
        id="rgm_48",
        name="RGM-48 'Ballista'",
        ship_class="Capital",
        price=450_000,
        durability=15_000,
        stats={
            "damage_min": 450.0,
            "damage_max": 450.0,
            "armor_piercing": 35.0,
            "range_min": 2_250.0,
            "range_max": 4_000.0,
            "optimal_range": 3_000.0,
            "accuracy": 125.0,
            "critical_offense": 100.0,
            "reload": 30.0,
            "power": 120.0,
            "firing_arc": 120.0,
            "turn_speed": 30.0,
            "projectile_speed": 110.0,
        },
        upgrades=("damage", "range"),
        description="Extreme-range DRADIS-guided missile platform for sieges.",
        tags=("missile", "siege"),
    ),
]


__all__ = ["EQUIPMENT_ITEMS"]

