"""Static equipment catalog data derived from design guidance."""
from __future__ import annotations

from typing import Dict, List, Sequence


EquipmentDefinition = Dict[str, object]


def _weapon(
    *,
    id: str,
    name: str,
    ship_class: str,
    price: int,
    durability: int,
    stats: Dict[str, float],
    upgrades: Sequence[str],
    description: str,
    tags: Sequence[str] = (),
) -> EquipmentDefinition:
    return {
        "id": id,
        "name": name,
        "slot_family": "weapon",
        "ship_class": ship_class,
        "level": 1,
        "durability": durability,
        "durability_max": durability,
        "price": price,
        "stats": stats,
        "upgrades": tuple(upgrades),
        "description": description,
        "tags": tuple(tags),
    }


def _module(
    *,
    id: str,
    name: str,
    slot_family: str,
    ship_class: str,
    price: int,
    durability: int,
    stats: Dict[str, float],
    upgrades: Sequence[str],
    description: str,
    tags: Sequence[str] = (),
) -> EquipmentDefinition:
    return {
        "id": id,
        "name": name,
        "slot_family": slot_family,
        "ship_class": ship_class,
        "level": 1,
        "durability": durability,
        "durability_max": durability,
        "price": price,
        "stats": stats,
        "upgrades": tuple(upgrades),
        "description": description,
        "tags": tuple(tags),
    }


EQUIPMENT_ITEMS: List[EquipmentDefinition] = [
    # Strike-class weapons -------------------------------------------------
    _weapon(
        id="mec_a6",
        name="MEC-A6 'Fang'",
        ship_class="Strike",
        price=10_000,
        durability=2_500,
        stats={
            "damage_min": 1.0,
            "damage_max": 10.0,
            "armor_piercing": 5.0,
            "range_min": 0.0,
            "range_max": 750.0,
            "optimal_range": 300.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 0.5,
            "power": 1.0,
            "firing_arc": 75.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Baseline autocannon balancing reach and stability.",
        tags=("balanced", "rapid_fire"),
    ),
    _weapon(
        id="mec_a6p",
        name="MEC-A6P 'Fang-P'",
        ship_class="Strike",
        price=10_000,
        durability=2_500,
        stats={
            "damage_min": 1.0,
            "damage_max": 10.0,
            "armor_piercing": 5.0,
            "range_min": 0.0,
            "range_max": 750.0,
            "optimal_range": 300.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 0.5,
            "power": 1.0,
            "firing_arc": 75.0,
        },
        upgrades=("damage", "critical_offense"),
        description="Precision variant trading future crit scaling for reach.",
        tags=("precision", "rapid_fire"),
    ),
    _weapon(
        id="mec_a8",
        name="MEC-A8 'Tornado'",
        ship_class="Strike",
        price=10_000,
        durability=2_500,
        stats={
            "damage_min": 1.0,
            "damage_max": 10.0,
            "armor_piercing": 5.0,
            "range_min": 0.0,
            "range_max": 600.0,
            "optimal_range": 250.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 0.4,
            "power": 1.0,
            "firing_arc": 75.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Faster cycle autocannon with tighter engagement envelope.",
        tags=("rapid_fire", "close_quarters"),
    ),
    _weapon(
        id="mec_a8p",
        name="MEC-A8P 'Tornado-P'",
        ship_class="Strike",
        price=10_000,
        durability=2_500,
        stats={
            "damage_min": 1.0,
            "damage_max": 10.0,
            "armor_piercing": 5.0,
            "range_min": 0.0,
            "range_max": 600.0,
            "optimal_range": 250.0,
            "accuracy": 400.0,
            "critical_offense": 100.0,
            "reload": 0.4,
            "power": 1.0,
            "firing_arc": 75.0,
        },
        upgrades=("damage", "critical_offense"),
        description="Crit-focused Tornado variant that retains the quick cycle.",
        tags=("precision", "rapid_fire"),
    ),
    _weapon(
        id="mel_n2",
        name="MEL-N2 'Needle'",
        ship_class="Strike",
        price=18_000,
        durability=2_500,
        stats={
            "damage_min": 8.0,
            "damage_max": 20.0,
            "armor_piercing": 18.0,
            "range_min": 0.0,
            "range_max": 900.0,
            "optimal_range": 500.0,
            "accuracy": 380.0,
            "critical_offense": 120.0,
            "reload": 0.9,
            "power": 3.0,
            "firing_arc": 60.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Precision railgun with long reach and strong armor punch.",
        tags=("precision", "railgun"),
    ),
    _weapon(
        id="mel_v1",
        name="MEL-V1 'Viper Pod'",
        ship_class="Strike",
        price=14_000,
        durability=2_500,
        stats={
            "damage_min": 5.0,
            "damage_max": 5.0,
            "burst_count": 4.0,
            "armor_piercing": 8.0,
            "range_min": 0.0,
            "range_max": 600.0,
            "optimal_range": 200.0,
            "accuracy": 360.0,
            "critical_offense": 80.0,
            "reload": 1.6,
            "power": 4.0,
            "firing_arc": 85.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Close-range rocket pod launching four micro-missiles per volley.",
        tags=("burst", "rocket"),
    ),
    _weapon(
        id="mel_s3",
        name="MEL-S3 'Stiletto'",
        ship_class="Strike",
        price=16_000,
        durability=2_500,
        stats={
            "damage_min": 3.0,
            "damage_max": 3.0,
            "damage_per_second": 3.0,
            "armor_piercing": 10.0,
            "range_min": 0.0,
            "range_max": 700.0,
            "optimal_range": 350.0,
            "accuracy": 420.0,
            "critical_offense": 90.0,
            "reload": 0.2,
            "power": 1.0,
            "firing_arc": 70.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Continuous beam emitter ideal for sustained tracking fire.",
        tags=("beam", "continuous"),
    ),
    _weapon(
        id="mel_w9",
        name="MEL-W9 'Wasp'",
        ship_class="Strike",
        price=22_000,
        durability=2_500,
        stats={
            "damage_min": 24.0,
            "damage_max": 24.0,
            "armor_piercing": 14.0,
            "range_min": 200.0,
            "range_max": 1_200.0,
            "optimal_range": 650.0,
            "accuracy": 410.0,
            "critical_offense": 110.0,
            "reload": 2.2,
            "power": 6.0,
            "firing_arc": 120.0,
        },
        upgrades=("damage", "reload"),
        description="Guided seeker missile with a forgiving soft-lock cone.",
        tags=("missile", "guided"),
    ),
    # Strike-class hull modules -------------------------------------------
    _module(
        id="strike_composite_plating",
        name="Strike Composite Plating",
        slot_family="hull",
        ship_class="Strike",
        price=8_000,
        durability=2_500,
        stats={
            "armor": 2.25,
            "hull_hp": 22.5,
            "acceleration": -0.3,
            "turn_accel": -0.75,
        },
        upgrades=("armor", "hull_hp"),
        description="Composite strike plating balancing armor and hull gains.",
        tags=("balanced", "survivability"),
    ),
    _module(
        id="strike_hull_plating",
        name="Strike Hull Plating",
        slot_family="hull",
        ship_class="Strike",
        price=8_000,
        durability=2_500,
        stats={
            "hull_hp": 45.0,
            "acceleration": -0.2,
            "turn_accel": -1.0,
        },
        upgrades=("hull_hp",),
        description="Additional hull bracing with noticeable inertia penalties.",
        tags=("survivability", "bulk"),
    ),
    _module(
        id="strike_armor_plating",
        name="Strike Armor Plating",
        slot_family="hull",
        ship_class="Strike",
        price=8_000,
        durability=2_500,
        stats={
            "armor": 4.5,
            "acceleration": -0.4,
            "turn_accel": -0.5,
        },
        upgrades=("armor",),
        description="Optimised armor layering at the expense of thrust response.",
        tags=("armor", "survivability"),
    ),
    _module(
        id="strike_ablative_lattice",
        name="Strike Ablative Lattice",
        slot_family="hull",
        ship_class="Strike",
        price=10_000,
        durability=2_500,
        stats={
            "armor": 6.0,
            "hull_hp": 10.0,
            "acceleration": -0.5,
            "turn_accel": -0.3,
        },
        upgrades=("armor", "hull_hp"),
        description="Heavy ablative mesh emphasizing armor over agility.",
        tags=("armor", "fortified"),
    ),
    _module(
        id="strike_bulkhead_reinforcement",
        name="Strike Bulkhead Reinforcement",
        slot_family="hull",
        ship_class="Strike",
        price=10_000,
        durability=2_500,
        stats={
            "hull_hp": 70.0,
            "acceleration": -0.3,
            "turn_accel": -1.2,
        },
        upgrades=("hull_hp",),
        description="Substantial internal bracing for maximum survivability.",
        tags=("survivability", "bulk"),
    ),
    _module(
        id="strike_reactive_plating",
        name="Strike Reactive Plating",
        slot_family="hull",
        ship_class="Strike",
        price=12_000,
        durability=2_500,
        stats={
            "armor": 3.0,
            "avoidance_rating": 5.0,
            "acceleration": -0.2,
        },
        upgrades=("armor", "avoidance_rating"),
        description="Reactive armor layer that modestly boosts avoidance.",
        tags=("defensive", "responsive"),
    ),
    # Strike-class engine modules -----------------------------------------
    _module(
        id="light_drive_overcharger",
        name="Light Drive Overcharger",
        slot_family="engine",
        ship_class="Strike",
        price=5_000,
        durability=2_500,
        stats={
            "max_speed": 1.25,
            "boost_speed": 1.25,
        },
        upgrades=("max_speed", "boost_speed"),
        description="Boosts cruise and sprint caps for straight-line pursuits.",
        tags=("speed", "cruise"),
    ),
    _module(
        id="light_turbo_boosters",
        name="Light Turbo Boosters",
        slot_family="engine",
        ship_class="Strike",
        price=5_000,
        durability=2_500,
        stats={
            "acceleration": 1.0,
            "boost_speed": 2.5,
        },
        upgrades=("acceleration", "boost_speed"),
        description="Quick-start shunts that prioritise sprint response.",
        tags=("acceleration", "boost"),
    ),
    _module(
        id="light_gyro_stabilization",
        name="Light Gyro-Stabilization",
        slot_family="engine",
        ship_class="Strike",
        price=5_000,
        durability=2_500,
        stats={
            "turn_rate": 2.5,
            "turn_accel": 2.5,
        },
        upgrades=("turn_rate", "turn_accel"),
        description="Gyro package that sharpens rotational control.",
        tags=("maneuvering",),
    ),
    _module(
        id="light_rcs_ducting",
        name="Light RCS Ducting",
        slot_family="engine",
        ship_class="Strike",
        price=5_000,
        durability=2_500,
        stats={
            "avoidance_rating": 15.0,
        },
        upgrades=("avoidance_rating",),
        description="Redirects exhaust for superior shot dodging.",
        tags=("defensive", "agility"),
    ),
    _module(
        id="light_afterburn_coupling",
        name="Light Afterburn Coupling",
        slot_family="engine",
        ship_class="Strike",
        price=7_500,
        durability=2_500,
        stats={
            "max_speed": 0.5,
            "boost_speed": 3.5,
            "acceleration": 0.5,
        },
        upgrades=("boost_speed", "acceleration"),
        description="Afterburner conduit prioritising sprint velocity.",
        tags=("boost", "acceleration"),
    ),
    _module(
        id="light_vectoring_nozzles",
        name="Light Vectoring Nozzles",
        slot_family="engine",
        ship_class="Strike",
        price=7_500,
        durability=2_500,
        stats={
            "turn_rate": 3.5,
            "turn_accel": 3.0,
            "acceleration": -0.2,
        },
        upgrades=("turn_rate", "turn_accel"),
        description="Vectoring jets trading a little thrust for tight turns.",
        tags=("maneuvering", "tradeoff"),
    ),
    _module(
        id="light_inertial_dampeners",
        name="Light Inertial Dampeners",
        slot_family="engine",
        ship_class="Strike",
        price=6_500,
        durability=2_500,
        stats={
            "acceleration": 1.5,
            "turn_accel": 1.0,
            "max_speed": -0.5,
        },
        upgrades=("acceleration", "turn_accel"),
        description="Dampening field improves responsiveness at top-speed cost.",
        tags=("maneuvering", "responsive"),
    ),
    _module(
        id="light_ecm_weave",
        name="Light ECM Weave",
        slot_family="engine",
        ship_class="Strike",
        price=9_000,
        durability=2_500,
        stats={
            "avoidance_rating": 12.0,
            "turn_rate": 1.0,
        },
        upgrades=("avoidance_rating",),
        description="Engine-hugging ECM mesh that shaves tracking locks.",
        tags=("defensive", "agility"),
    ),
    # Escort-class weapons -------------------------------------------------
    _weapon(
        id="mec_e12",
        name="MEC-E12 'Claw'",
        ship_class="Escort",
        price=15_000,
        durability=7_500,
        stats={
            "damage_min": 10.0,
            "damage_max": 25.0,
            "armor_piercing": 15.0,
            "range_min": 0.0,
            "range_max": 1_150.0,
            "optimal_range": 450.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 1.5,
            "power": 6.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Balanced medium cannon battery for flexible skirmishing.",
        tags=("balanced", "medium_cannon"),
    ),
    _weapon(
        id="mec_e13",
        name="MEC-E13 'Hurricane'",
        ship_class="Escort",
        price=15_000,
        durability=7_500,
        stats={
            "damage_min": 10.0,
            "damage_max": 25.0,
            "armor_piercing": 15.0,
            "range_min": 0.0,
            "range_max": 900.0,
            "optimal_range": 350.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 1.2,
            "power": 6.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Rapid-firing close-range cannon battery for aggressive Escorts.",
        tags=("rapid_fire", "medium_cannon"),
    ),
    _weapon(
        id="mec_e17",
        name="MEC-E17 'Falcon'",
        ship_class="Escort",
        price=15_000,
        durability=7_500,
        stats={
            "damage_min": 10.0,
            "damage_max": 25.0,
            "armor_piercing": 15.0,
            "range_min": 0.0,
            "range_max": 1_350.0,
            "optimal_range": 550.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 1.8,
            "power": 6.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Longer-ranged escort cannon prioritising safe standoff fire.",
        tags=("precision", "medium_cannon"),
    ),
    _weapon(
        id="hd_m50p",
        name="HD-M50P 'Thunderbolt-P'",
        ship_class="Escort",
        price=15_000,
        durability=7_500,
        stats={
            "damage_min": 40.0,
            "damage_max": 100.0,
            "armor_piercing": 25.0,
            "range_min": 200.0,
            "range_max": 1_350.0,
            "optimal_range": 850.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 12.5,
            "power": 50.0,
            "firing_arc": 180.0,
            "turn_speed": 75.0,
            "projectile_speed": 100.0,
        },
        upgrades=("damage", "critical_offense"),
        description="Precision missile rack rewarding crit-stacking escort tactics.",
        tags=("missile", "guided"),
    ),
    _weapon(
        id="hd_m63",
        name="HD-M63 'Scorpio'",
        ship_class="Escort",
        price=15_000,
        durability=7_500,
        stats={
            "damage_min": 40.0,
            "damage_max": 100.0,
            "armor_piercing": 25.0,
            "range_min": 200.0,
            "range_max": 1_600.0,
            "optimal_range": 900.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 15.0,
            "power": 50.0,
            "firing_arc": 180.0,
            "turn_speed": 75.0,
            "projectile_speed": 100.0,
        },
        upgrades=("damage", "range"),
        description="Long-range missile battery focused on deliberate volleys.",
        tags=("missile", "long_range"),
    ),
    _weapon(
        id="hd_m63p",
        name="HD-M63P 'Scorpio-P'",
        ship_class="Escort",
        price=15_000,
        durability=7_500,
        stats={
            "damage_min": 40.0,
            "damage_max": 100.0,
            "armor_piercing": 25.0,
            "range_min": 200.0,
            "range_max": 1_600.0,
            "optimal_range": 900.0,
            "accuracy": 335.0,
            "critical_offense": 100.0,
            "reload": 15.0,
            "power": 50.0,
            "firing_arc": 180.0,
            "turn_speed": 75.0,
            "projectile_speed": 100.0,
        },
        upgrades=("damage", "critical_offense"),
        description="Precision Scorpio launcher emphasising critical strike chains.",
        tags=("missile", "long_range"),
    ),
    # Line-class weapons ---------------------------------------------------
    _weapon(
        id="mec_l31",
        name="MEC-L31 'Talon'",
        ship_class="Line",
        price=20_000,
        durability=17_500,
        stats={
            "damage_min": 35.0,
            "damage_max": 70.0,
            "armor_piercing": 35.0,
            "range_min": 0.0,
            "range_max": 1_700.0,
            "optimal_range": 675.0,
            "accuracy": 125.0,
            "critical_offense": 100.0,
            "reload": 4.0,
            "power": 25.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Baseline heavy cannon battery for sustained line combat.",
        tags=("heavy_cannon", "mid_range"),
    ),
    _weapon(
        id="mec_l34",
        name="MEC-L34 'Cyclone'",
        ship_class="Line",
        price=20_000,
        durability=17_500,
        stats={
            "damage_min": 35.0,
            "damage_max": 70.0,
            "armor_piercing": 35.0,
            "range_min": 0.0,
            "range_max": 1_350.0,
            "optimal_range": 550.0,
            "accuracy": 125.0,
            "critical_offense": 100.0,
            "reload": 3.2,
            "power": 25.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Faster-cycling heavy cannon ideal for brawling ranges.",
        tags=("heavy_cannon", "close_quarters"),
    ),
    _weapon(
        id="mec_l35",
        name="MEC-L35 'Eagle'",
        ship_class="Line",
        price=20_000,
        durability=17_500,
        stats={
            "damage_min": 35.0,
            "damage_max": 70.0,
            "armor_piercing": 35.0,
            "range_min": 0.0,
            "range_max": 2_000.0,
            "optimal_range": 800.0,
            "accuracy": 125.0,
            "critical_offense": 100.0,
            "reload": 4.8,
            "power": 25.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Long-range heavy cannon that trades rate of fire for reach.",
        tags=("heavy_cannon", "long_range"),
    ),
    _weapon(
        id="hd_h40",
        name="HD-H40 'Stormstrike'",
        ship_class="Line",
        price=20_000,
        durability=17_500,
        stats={
            "damage_min": 55.0,
            "damage_max": 150.0,
            "armor_piercing": 35.0,
            "range_min": 200.0,
            "range_max": 1_800.0,
            "optimal_range": 1_000.0,
            "accuracy": 125.0,
            "critical_offense": 100.0,
            "reload": 15.0,
            "power": 100.0,
            "firing_arc": 180.0,
            "turn_speed": 30.0,
            "projectile_speed": 80.0,
        },
        upgrades=("damage", "range"),
        description="Guided heavy missile battery delivering punishing alpha.",
        tags=("missile", "heavy"),
    ),
    _weapon(
        id="mec_l39f",
        name="MEC-L39F 'Landslide'",
        ship_class="Line",
        price=20_000,
        durability=17_500,
        stats={
            "damage_min": 1.0,
            "damage_max": 35.0,
            "armor_piercing": 15.0,
            "range_min": 500.0,
            "range_max": 800.0,
            "optimal_range": 800.0,
            "accuracy": 300.0,
            "critical_offense": 100.0,
            "reload": 1.0,
            "power": 7.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "range"),
        description="Area flak battery for anti-missile and strike suppression.",
        tags=("flak", "defensive"),
    ),
    _weapon(
        id="mec_l30p",
        name="MEC-L30P 'Brushfire'",
        ship_class="Line",
        price=20_000,
        durability=17_500,
        stats={
            "damage_min": 1.0,
            "damage_max": 5.0,
            "armor_piercing": 5.0,
            "range_min": 0.0,
            "range_max": 540.0,
            "optimal_range": 400.0,
            "accuracy": 500.0,
            "critical_offense": 100.0,
            "reload": 0.5,
            "power": 3.5,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "range"),
        description="Close-in defense battery focused on missile interception.",
        tags=("point_defense", "ciws"),
    ),
    _weapon(
        id="hd_h48",
        name="HD-H48 'Ballista'",
        ship_class="Line",
        price=20_000,
        durability=17_500,
        stats={
            "damage_min": 55.0,
            "damage_max": 150.0,
            "armor_piercing": 35.0,
            "range_min": 200.0,
            "range_max": 2_000.0,
            "optimal_range": 1_200.0,
            "accuracy": 125.0,
            "critical_offense": 100.0,
            "reload": 18.0,
            "power": 100.0,
            "firing_arc": 180.0,
            "turn_speed": 30.0,
            "projectile_speed": 80.0,
        },
        upgrades=("damage", "range"),
        description="Extended-range heavy missile battery for bombardment.",
        tags=("missile", "long_range"),
    ),
    # Capital-class weapons -----------------------------------------------
    _weapon(
        id="hag_mk16a",
        name="HAG-MK16A 'Gram'",
        ship_class="Capital",
        price=500_000,
        durability=20_000,
        stats={
            "damage_min": 75.0,
            "damage_max": 135.0,
            "armor_piercing": 35.0,
            "range_min": 2_300.0,
            "range_max": 4_000.0,
            "optimal_range": 2_750.0,
            "accuracy": 125.0,
            "critical_offense": 100.0,
            "reload": 8.0,
            "power": 64.0,
            "firing_arc": 35.0,
        },
        upgrades=("damage", "optimal_range"),
        description="Siege artillery cannon built for devastating broadsides.",
        tags=("artillery", "siege"),
    ),
    _weapon(
        id="pd_x30p",
        name="PD-X30P 'Wildfire'",
        ship_class="Capital",
        price=300_000,
        durability=25_000,
        stats={
            "damage_min": 3.0,
            "damage_max": 7.0,
            "armor_piercing": 5.0,
            "range_min": 0.0,
            "range_max": 1_200.0,
            "optimal_range": 500.0,
            "accuracy": 500.0,
            "critical_offense": 100.0,
            "reload": 0.5,
            "power": 3.5,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "range"),
        description="Capital CIWS battery for layered close-in defence.",
        tags=("point_defense", "ciws"),
    ),
    _weapon(
        id="m_37a",
        name="M-37A 'Fusillade'",
        ship_class="Capital",
        price=450_000,
        durability=25_000,
        stats={
            "damage_min": 20.0,
            "damage_max": 30.0,
            "armor_piercing": 15.0,
            "range_min": 1_000.0,
            "range_max": 1_400.0,
            "optimal_range": 1_200.0,
            "accuracy": 300.0,
            "critical_offense": 100.0,
            "reload": 1.0,
            "power": 5.0,
            "firing_arc": 45.0,
        },
        upgrades=("damage", "range"),
        description="Spot flak turret covering narrow arcs with concentrated bursts.",
        tags=("flak", "defensive"),
    ),
    _weapon(
        id="m_39f",
        name="M-39F 'Avalanche'",
        ship_class="Capital",
        price=350_000,
        durability=20_000,
        stats={
            "damage_min": 10.0,
            "damage_max": 28.0,
            "armor_piercing": 15.0,
            "range_min": 900.0,
            "range_max": 1_500.0,
            "optimal_range": 1_200.0,
            "accuracy": 300.0,
            "critical_offense": 100.0,
            "reload": 1.0,
            "power": 7.0,
            "firing_arc": 180.0,
        },
        upgrades=("damage", "range"),
        description="Wide-arc flak battery saturating approach vectors with bursts.",
        tags=("flak", "defensive"),
    ),
    _weapon(
        id="ram_179a",
        name="RAM-179A 'Stormstrike'",
        ship_class="Capital",
        price=280_000,
        durability=25_000,
        stats={
            "damage_min": 250.0,
            "damage_max": 250.0,
            "armor_piercing": 35.0,
            "range_min": 0.0,
            "range_max": 1_800.0,
            "optimal_range": 1_100.0,
            "accuracy": 125.0,
            "critical_offense": 100.0,
            "reload": 20.0,
            "power": 80.0,
            "firing_arc": 360.0,
            "turn_speed": 45.0,
            "projectile_speed": 95.0,
        },
        upgrades=("damage", "range"),
        description="360° guided missile rack for heavy anti-ship salvos.",
        tags=("missile", "guided"),
    ),
    _weapon(
        id="rgm_48",
        name="RGM-48 'Ballista'",
        ship_class="Capital",
        price=450_000,
        durability=15_000,
        stats={
            "damage_min": 450.0,
            "damage_max": 450.0,
            "armor_piercing": 35.0,
            "range_min": 2_250.0,
            "range_max": 4_000.0,
            "optimal_range": 3_000.0,
            "accuracy": 125.0,
            "critical_offense": 100.0,
            "reload": 30.0,
            "power": 120.0,
            "firing_arc": 120.0,
            "turn_speed": 30.0,
            "projectile_speed": 110.0,
        },
        upgrades=("damage", "range"),
        description="Extreme-range DRADIS-guided missile platform for sieges.",
        tags=("missile", "siege"),
    ),
]


__all__ = ["EQUIPMENT_ITEMS"]

