"""Ship frame definitions derived from `ship_guidance`.

This module provides structured data so tests and the ContentManager
can bootstrap ship frames without relying on the old `exemplars.json` asset.
"""

GUIDANCE_SHIP_DATA = [{'counterpart': None,
  'economy': {'operating': {'boost': 0.5, 'ftl': 20}, 'purchase': {'tylium': 100000}},
  'equipment': {'modules': {},
                'weapons': {'hp_viper2_port_inner': 'mec_a6p',
                            'hp_viper2_port_outer': 'mec_a6',
                            'hp_viper2_starboard_inner': 'siw_9m_wasp',
                            'hp_viper2_starboard_outer': 'mec_a6'}},
  'faction': 'Colonial Fleet',
  'hardpoints': [{'gimbal': 28,
                  'group': 'primary',
                  'id': 'hp_viper2_port_outer',
                  'position': [-1.2, -0.08, 1.2],
                  'slot': 'cannon',
                  'tracking_speed': 250},
                 {'gimbal': 24,
                  'group': 'primary',
                  'id': 'hp_viper2_port_inner',
                  'position': [-0.7, -0.1, 2.0],
                  'slot': 'cannon',
                  'tracking_speed': 240},
                 {'gimbal': 28,
                  'group': 'aux',
                  'id': 'hp_viper2_starboard_inner',
                  'position': [0.7, -0.1, 2.0],
                  'slot': 'launcher',
                  'tracking_speed': 240},
                 {'gimbal': 28,
                  'group': 'primary',
                  'id': 'hp_viper2_starboard_outer',
                  'position': [1.2, -0.08, 1.2],
                  'slot': 'cannon',
                  'tracking_speed': 250}],
  'id': 'viper_mk_ii',
  'level_requirement': 1,
  'name': 'Viper Mk II',
  'notes': 'Baseline Colonial strike craft with extreme handling and avoidance.',
  'role': 'Interceptor',
  'role_bonuses': ['Interceptor frame provides additional engine capacity.'],
  'size': 'Strike',
  'slots': {'computer': 2,
            'engine': {'advanced_delta': 1, 'advanced_total': 6, 'base': 5},
            'hull': 2,
            'weapons': {'weapons': {'advanced_delta': 1,
                                    'advanced_total': 5,
                                    'base': 4},
                        'guns': 3,
                        'launchers': 1}},
  'stats': {'acceleration': {'advanced_delta': 2.7,
                             'advanced_total': 16.2,
                             'base': 13.5},
            'armor_value': 5,
            'avoidance_fading': 0.75,
            'avoidance_rating': 510,
            'boost_acceleration': 1.5,
            'boost_cost': 0.5,
            'boost_speed': {'advanced_delta': 20, 'advanced_total': 110, 'base': 90},
            'critical_defense': 80,
            'dradis_range_base': 1000,
            'dradis_range_max': 2000,
            'durability': {'advanced_delta': 4500,
                           'advanced_total': 13500,
                           'base': 9000},
            'durability_bonus': 0,
            'emitter_rating': 100,
            'firewall_rating': 100,
            'ftl_charge_time': 15,
            'ftl_cooldown': 35,
            'ftl_cost': 20,
            'ftl_range': 4.5,
            'hull_points': {'advanced_delta': 135, 'advanced_total': 585, 'base': 450},
            'hull_recovery_per_sec': {'advanced_delta': 2.0,
                                      'advanced_total': 4.5,
                                      'base': 2.5},
            'inertial_compensation': 175,
            'max_radiation_level': 80,
            'pitch_acceleration': 55,
            'pitch_speed': 55,
            'power_points': {'advanced_delta': 50, 'advanced_total': 150, 'base': 100},
            'power_recovery_per_sec': 5,
            'radioactive_decay': 0.5,
            'radioresistance': 0,
            'roll_acceleration': 748,
            'roll_speed': 182,
            'speed': {'advanced_delta': 5, 'advanced_total': 60, 'base': 55},
            'strafe_acceleration': 0,
            'strafe_speed': 0,
            'transponder_power_cost': 0,
            'turn_accel': 55,
            'turn_rate': {'advanced_delta': 3, 'advanced_total': 58, 'base': 55},
            'visual_range': 200,
            'yaw_acceleration': 55,
            'yaw_speed': 55},
  'traits': ['Iconic Colonial interceptor built for pursuit and missile denial.'],
  'upgrade_to': 'advanced_viper_mk_ii'},
 {'counterpart': 'Cylon War Raider',
  'economy': {'operating': {'boost': 0.75, 'ftl': 30}, 'purchase': {'tylium': 45000}},
  'equipment': {'modules': {},
                'weapons': {'hp_viper_center': 'mec_a8',
                            'hp_viper_missile': 'siw_9m_wasp',
                            'hp_viper_port': 'mec_a6',
                            'hp_viper_starboard': 'mec_a6p'}},
  'faction': 'Colonial Fleet',
  'hardpoints': [{'gimbal': 24,
                  'group': 'primary',
                  'id': 'hp_viper_port',
                  'position': [-0.8, -0.12, 2.4],
                  'slot': 'cannon',
                  'tracking_speed': 240},
                 {'gimbal': 24,
                  'group': 'primary',
                  'id': 'hp_viper_starboard',
                  'position': [0.8, -0.12, 2.4],
                  'slot': 'cannon',
                  'tracking_speed': 240},
                 {'gimbal': 28,
                  'group': 'primary',
                  'id': 'hp_viper_center',
                  'position': [0.0, -0.18, 2.6],
                  'slot': 'cannon',
                  'tracking_speed': 220},
                 {'gimbal': 36,
                  'group': 'aux',
                  'id': 'hp_viper_missile',
                  'position': [0.0, -0.4, 1.5],
                  'slot': 'launcher',
                  'tracking_speed': 200}],
  'id': 'viper_mk_vii',
  'level_requirement': 1,
  'name': 'Viper Mk VII',
  'notes': 'Standard Fleet striker balanced for long sorties.',
  'role': 'Multi-Role',
  'role_bonuses': ['Flexible strike package supports missile or PD conversions.'],
  'size': 'Strike',
  'slots': {'computer': 3,
            'engine': 3,
            'hull': 3,
            'weapons': {'weapons': 4, 'guns': 3, 'launchers': 1}},
  'stats': {'acceleration': 12,
            'armor_value': 5,
            'avoidance_fading': 0.75,
            'avoidance_rating': 510,
            'boost_acceleration': 4,
            'boost_cost': 0.75,
            'boost_speed': 85,
            'critical_defense': 80,
            'dradis_range_base': 1000,
            'dradis_range_max': 2000,
            'durability': 9000,
            'durability_bonus': 0,
            'emitter_rating': 100,
            'firewall_rating': 100,
            'ftl_charge_time': 15,
            'ftl_cooldown': 35,
            'ftl_cost': 30,
            'ftl_range': 4.5,
            'hull_points': 585,
            'hull_recovery_per_sec': 4.5,
            'inertial_compensation': 100,
            'max_radiation_level': 100,
            'pitch_acceleration': 55,
            'pitch_speed': 50,
            'power_points': 150,
            'power_recovery_per_sec': 5,
            'radioactive_decay': 0.6,
            'radioresistance': 0,
            'roll_acceleration': 748,
            'roll_speed': 200,
            'speed': 55,
            'strafe_acceleration': 0,
            'strafe_speed': 0,
            'transponder_power_cost': 0,
            'turn_accel': 55,
            'turn_rate': 50,
            'visual_range': 200,
            'yaw_acceleration': 55,
            'yaw_speed': 50},
  'traits': ['High avoidance and responsive handling reward precise flying.'],
  'upgrade_to': 'advanced_viper_mk_vii'},
 {'counterpart': None,
  'economy': {'operating': {'boost': 0.6, 'ftl': 30}, 'purchase': {'tylium': 45000}},
  'equipment': {'modules': {},
                'weapons': {'hp_raptor_dorsal': 'siw_9m_wasp',
                            'hp_raptor_port': 'gopher_light_mining_cannon',
                            'hp_raptor_starboard': 'gopher_light_mining_cannon'}},
  'faction': 'Colonial Fleet',
  'hardpoints': [{'gimbal': 30,
                  'group': 'primary',
                  'id': 'hp_raptor_port',
                  'position': [-0.9, -0.1, 1.6],
                  'slot': 'cannon',
                  'tracking_speed': 200},
                 {'gimbal': 30,
                  'group': 'primary',
                  'id': 'hp_raptor_starboard',
                  'position': [0.9, -0.1, 1.6],
                  'slot': 'cannon',
                  'tracking_speed': 200},
                 {'gimbal': 36,
                  'group': 'aux',
                  'id': 'hp_raptor_dorsal',
                  'position': [0.0, 0.4, 2.0],
                  'slot': 'launcher',
                  'tracking_speed': 180}],
  'id': 'raptor_fr',
  'level_requirement': 1,
  'name': 'Raptor FR',
  'notes': 'Fleet reconnaissance variant optimized for EW and scouting.',
  'role': 'Command',
  'role_bonuses': ['Command bonus reduces transponder power usage by 75.'],
  'size': 'Strike',
  'slots': {'computer': 5,
            'engine': 4,
            'hull': 1,
            'weapons': {'weapons': 3, 'guns': 2, 'launchers': 1}},
  'stats': {'acceleration': 10,
            'armor_value': 5,
            'avoidance_fading': 0.75,
            'avoidance_rating': 500,
            'boost_acceleration': 4,
            'boost_cost': 0.6,
            'boost_speed': 77.5,
            'critical_defense': 100,
            'dradis_range_base': 4000,
            'dradis_range_max': 4000,
            'durability': 10000,
            'durability_bonus': 0,
            'emitter_rating': 200,
            'firewall_rating': 200,
            'ftl_charge_time': 12.5,
            'ftl_cooldown': 30,
            'ftl_cost': 30,
            'ftl_range': 6.75,
            'hull_points': 650,
            'hull_recovery_per_sec': 5,
            'inertial_compensation': 100,
            'max_radiation_level': 130,
            'pitch_acceleration': 47.5,
            'pitch_speed': 47.5,
            'power_points': 200,
            'power_recovery_per_sec': 6,
            'radioactive_decay': 0.8,
            'radioresistance': 0,
            'roll_acceleration': 60,
            'roll_speed': 60,
            'speed': 52.5,
            'strafe_acceleration': 0,
            'strafe_speed': 0,
            'transponder_power_cost': -75,
            'turn_accel': 47.5,
            'turn_rate': 47.5,
            'visual_range': 600,
            'yaw_acceleration': 47.5,
            'yaw_speed': 47.5},
  'traits': ['Recon strike with expanded sensor suite and computer capacity.'],
  'upgrade_to': None},
 {'counterpart': None,
  'economy': {'operating': {'boost': 0.5, 'ftl': 30}, 'purchase': {'tylium': 23000}},
  'equipment': {'modules': {},
                'weapons': {'hp_viper3_center': 'siw_9m_wasp',
                            'hp_viper3_port': 'mec_a8',
                            'hp_viper3_starboard': 'mec_a8p'}},
  'faction': 'Colonial Fleet',
  'hardpoints': [{'gimbal': 26,
                  'group': 'primary',
                  'id': 'hp_viper3_port',
                  'position': [-0.85, -0.14, 2.2],
                  'slot': 'cannon',
                  'tracking_speed': 235},
                 {'gimbal': 26,
                  'group': 'primary',
                  'id': 'hp_viper3_starboard',
                  'position': [0.85, -0.14, 2.2],
                  'slot': 'cannon',
                  'tracking_speed': 235},
                 {'gimbal': 34,
                  'group': 'aux',
                  'id': 'hp_viper3_center',
                  'position': [0.0, -0.18, 2.5],
                  'slot': 'launcher',
                  'tracking_speed': 210}],
  'id': 'viper_mk_iii',
  'level_requirement': 1,
  'name': 'Viper Mk III',
  'notes': 'Fits between interceptor and recon frames as the workhorse multi-role '
           'Viper.',
  'role': 'Multi-Role',
  'role_bonuses': [],
  'size': 'Strike',
  'slots': {'computer': 2,
            'engine': 3,
            'hull': 3,
            'weapons': {'weapons': 3, 'guns': 2, 'launchers': 1}},
  'stats': {'acceleration': 14,
            'armor_value': 5,
            'avoidance_fading': 0.75,
            'avoidance_rating': 510,
            'boost_acceleration': 4.5,
            'boost_cost': 0.5,
            'boost_speed': 100,
            'critical_defense': 80,
            'dradis_range_base': 1000,
            'dradis_range_max': 2000,
            'durability': 4500,
            'durability_bonus': 0,
            'emitter_rating': 100,
            'firewall_rating': 100,
            'ftl_charge_time': 15,
            'ftl_cooldown': 35,
            'ftl_cost': 30,
            'ftl_range': 4.5,
            'hull_points': 515,
            'hull_recovery_per_sec': 3.5,
            'inertial_compensation': 100,
            'max_radiation_level': 80,
            'pitch_acceleration': 55,
            'pitch_speed': 51,
            'power_points': 100,
            'power_recovery_per_sec': 5.2,
            'radioactive_decay': 0.5,
            'radioresistance': 0,
            'roll_acceleration': 748,
            'roll_speed': 180,
            'speed': 55,
            'strafe_acceleration': 0,
            'strafe_speed': 0,
            'transponder_power_cost': 0,
            'turn_accel': 55,
            'turn_rate': 51,
            'visual_range': 200,
            'yaw_acceleration': 55,
            'yaw_speed': 51},
  'traits': ['Balanced strike with flexible loadout and reliable handling.'],
  'upgrade_to': None},
 {'counterpart': None,
  'economy': {'operating': {'boost': 0.7, 'ftl': 30}, 'purchase': {'tylium': 36000}},
  'equipment': {'modules': {},
                'weapons': {'hp_rhino_port_front': 'mec_a8',
                            'hp_rhino_port_rear': 'mec_a6p',
                            'hp_rhino_starboard_front': 'mec_a8',
                            'hp_rhino_starboard_rear': 'siw_9m_wasp'}},
  'faction': 'Colonial Fleet',
  'hardpoints': [{'gimbal': 32,
                  'group': 'primary',
                  'id': 'hp_rhino_port_front',
                  'position': [-0.9, -0.05, 1.8],
                  'slot': 'cannon',
                  'tracking_speed': 210},
                 {'gimbal': 30,
                  'group': 'primary',
                  'id': 'hp_rhino_port_rear',
                  'position': [-1.1, -0.02, 0.6],
                  'slot': 'cannon',
                  'tracking_speed': 190},
                 {'gimbal': 32,
                  'group': 'primary',
                  'id': 'hp_rhino_starboard_front',
                  'position': [0.9, -0.05, 1.8],
                  'slot': 'cannon',
                  'tracking_speed': 210},
                 {'gimbal': 32,
                  'group': 'aux',
                  'id': 'hp_rhino_starboard_rear',
                  'position': [1.1, -0.02, 0.6],
                  'slot': 'launcher',
                  'tracking_speed': 190}],
  'id': 'rhino_strike',
  'level_requirement': 1,
  'name': 'Rhino',
  'notes': 'Designed to brawl on objectives while shrugging off punishment.',
  'role': 'Assault',
  'role_bonuses': ['Assault frame grants additional hull module capacity.'],
  'size': 'Strike',
  'slots': {'computer': 2,
            'engine': 2,
            'hull': 5,
            'weapons': {'weapons': 4, 'guns': 3, 'launchers': 1}},
  'stats': {'acceleration': 8,
            'armor_value': 10,
            'avoidance_fading': 0.75,
            'avoidance_rating': 490,
            'boost_acceleration': 7,
            'boost_cost': 0.7,
            'boost_speed': 75,
            'critical_defense': 120,
            'dradis_range_base': 1000,
            'dradis_range_max': 2500,
            'durability': 11000,
            'durability_bonus': 0,
            'emitter_rating': 150,
            'firewall_rating': 150,
            'ftl_charge_time': 15,
            'ftl_cooldown': 32.5,
            'ftl_cost': 30,
            'ftl_range': 5,
            'hull_points': 715,
            'hull_recovery_per_sec': 5.5,
            'inertial_compensation': 100,
            'max_radiation_level': 130,
            'pitch_acceleration': 45,
            'pitch_speed': 45,
            'power_points': 150,
            'power_recovery_per_sec': 5,
            'radioactive_decay': 0.8,
            'radioresistance': 0,
            'roll_acceleration': 450,
            'roll_speed': 101.25,
            'speed': 50,
            'strafe_acceleration': 0,
            'strafe_speed': 0,
            'transponder_power_cost': 0,
            'turn_accel': 45,
            'turn_rate': 45,
            'visual_range': 250,
            'yaw_acceleration': 45,
            'yaw_speed': 45},
  'traits': ['Heavy strike that trades top speed for armor and durability.'],
  'upgrade_to': None},
 {'counterpart': None,
  'economy': {'operating': {'boost': 0.5, 'ftl': 1}, 'purchase': {'tylium': 35000}},
  'equipment': {'modules': {},
                'weapons': {'hp_raven_port': 'mec_a6p',
                            'hp_raven_starboard': 'mec_a8p'}},
  'faction': 'Colonial Fleet',
  'hardpoints': [{'gimbal': 34,
                  'group': 'primary',
                  'id': 'hp_raven_port',
                  'position': [-0.6, -0.05, 1.9],
                  'slot': 'gun',
                  'tracking_speed': 250},
                 {'gimbal': 34,
                  'group': 'primary',
                  'id': 'hp_raven_starboard',
                  'position': [0.6, -0.05, 1.9],
                  'slot': 'gun',
                  'tracking_speed': 250}],
  'id': 'raven_mk_vi_r',
  'level_requirement': 1,
  'name': 'Raven Mk VI-R',
  'notes': 'Optimized for deep reconnaissance with efficient jump profile.',
  'role': 'Force Recon',
  'role_bonuses': ['Force recon chassis enjoys extremely low FTL costs.'],
  'size': 'Strike',
  'slots': {'computer': 1,
            'engine': 2,
            'hull': 2,
            'weapons': {'weapons': 0, 'guns': 2, 'launchers': 0}},
  'stats': {'acceleration': 13,
            'armor_value': 0,
            'avoidance_fading': 0.75,
            'avoidance_rating': 520,
            'boost_acceleration': 1.25,
            'boost_cost': 0.5,
            'boost_speed': 90,
            'critical_defense': 60,
            'dradis_range_base': 1000,
            'dradis_range_max': 2250,
            'durability': 3500,
            'durability_bonus': 0,
            'emitter_rating': 100,
            'firewall_rating': 100,
            'ftl_charge_time': 15,
            'ftl_cooldown': 35,
            'ftl_cost': 1,
            'ftl_range': 10.5,
            'hull_points': 350,
            'hull_recovery_per_sec': 3,
            'inertial_compensation': 175,
            'max_radiation_level': 70,
            'pitch_acceleration': 75,
            'pitch_speed': 52,
            'power_points': 120,
            'power_recovery_per_sec': 3,
            'radioactive_decay': 0.4,
            'radioresistance': 0,
            'roll_acceleration': 750,
            'roll_speed': 90,
            'speed': 70,
            'strafe_acceleration': 80,
            'strafe_speed': 0,
            'transponder_power_cost': 0,
            'turn_accel': 90,
            'turn_rate': 50,
            'visual_range': 225,
            'yaw_acceleration': 90,
            'yaw_speed': 50},
  'traits': ['Low-signature scout with enhanced DRADIS reach and minimal armament.'],
  'upgrade_to': None},
 {'counterpart': 'Spectre',
  'economy': {'operating': {'boost': 1.8, 'ftl': 80}, 'purchase': {'tylium': 60000}},
  'equipment': {'modules': {},
                'weapons': {'hp_glaive_dorsal': 'hd_m50p',
                            'hp_glaive_front': 'mec_e13',
                            'hp_glaive_launcher': 'hd_m63p',
                            'hp_glaive_port': 'mec_e12',
                            'hp_glaive_starboard': 'mec_e12',
                            'hp_glaive_ventral': 'mec_e17'}},
  'faction': 'Colonial Fleet',
  'hardpoints': [{'gimbal': 32,
                  'group': 'primary',
                  'id': 'hp_glaive_front',
                  'position': [0.0, 0.2, 3.2],
                  'slot': 'cannon',
                  'tracking_speed': 220},
                 {'gimbal': 45,
                  'group': 'primary',
                  'id': 'hp_glaive_port',
                  'position': [-1.8, 0.0, 1.4],
                  'slot': 'cannon',
                  'tracking_speed': 180},
                 {'gimbal': 45,
                  'group': 'primary',
                  'id': 'hp_glaive_starboard',
                  'position': [1.8, 0.0, 1.4],
                  'slot': 'cannon',
                  'tracking_speed': 180},
                 {'gimbal': 55,
                  'group': 'aux',
                  'id': 'hp_glaive_dorsal',
                  'position': [0.0, 0.9, 1.2],
                  'slot': 'launcher',
                  'tracking_speed': 160},
                 {'gimbal': 55,
                  'group': 'primary',
                  'id': 'hp_glaive_ventral',
                  'position': [0.0, -0.9, 1.2],
                  'slot': 'cannon',
                  'tracking_speed': 160},
                 {'gimbal': 40,
                  'group': 'aux',
                  'id': 'hp_glaive_launcher',
                  'position': [0.0, -0.4, 2.6],
                  'slot': 'launcher',
                  'tracking_speed': 160}],
  'id': 'glaive_command',
  'level_requirement': 1,
  'name': 'Glaive Command',
  'notes': 'Command-focused Escort with 5 Computer slots and a large energy '
           'pool, suitable for EW/support builds.',
  'role': 'Command',
  'role_bonuses': ['Role Bonus: −50 Transponder Power Cost (Command bonus).'],
  'size': 'Escort',
  'slots': {'computer': 5,
            'engine': 2,
            'hull': 2,
            'weapons': {'weapons': 6,
                        'guns': 0,
                        'launchers': 0,
                        'defensive': 0,
                        'special': 0}},
  'stats': {'acceleration': 5,
            'armor_value': 25,
            'avoidance_fading': 0.75,
            'avoidance_rating': 270,
            'boost_acceleration': 1.5,
            'boost_cost': 1.8,
            'boost_speed': 57.5,
            'critical_defense': 100,
            'dradis_range_base': 1250,
            'dradis_range_max': 3500,
            'durability': 30000,
            'durability_bonus': 0,
            'emitter_rating': 200,
            'firewall_rating': 200,
            'ftl_charge_time': 20,
            'ftl_cooldown': 30,
            'ftl_cost': 80,
            'ftl_range': 8.25,
            'hull_points': 1700,
            'hull_recovery_per_sec': 15,
            'inertial_compensation': 50,
            'max_radiation_level': 160,
            'pitch_acceleration': 22.5,
            'pitch_speed': 22.5,
            'power_points': 330,
            'power_recovery_per_sec': 12,
            'radioactive_decay': 1,
            'radioresistance': 0,
            'roll_acceleration': 39.375,
            'roll_speed': 39.375,
            'speed': 37.5,
            'strafe_acceleration': 0,
            'strafe_speed': 0,
            'transponder_power_cost': -50,
            'turn_accel': 22.5,
            'turn_rate': 22.5,
            'visual_range': 750,
            'yaw_acceleration': 22.5,
            'yaw_speed': 22.5},
  'traits': ['Known for broad firing coverage via head and ring mounts with few '
             'blind spots.',
            'Pilots often roll to shield the exposed underside during attack '
            'runs.',
            'Trades agility for firepower and electronics; excels when '
            'screened by Strikes.'],
  'upgrade_to': 'advanced_glaive'},
 {'counterpart': None,
  'economy': {'operating': {'boost': 1.5, 'ftl': 80}, 'purchase': {'cubits': 600000}},
  'equipment': {'modules': {},
                'weapons': {'hp_scythe_port_front': 'hd_m63',
                            'hp_scythe_port_rear': 'mec_e17',
                            'hp_scythe_starboard_front': 'hd_m63',
                            'hp_scythe_starboard_rear': 'mec_e17'}},
  'faction': 'Colonial Fleet',
  'hardpoints': [{'gimbal': 32,
                  'group': 'aux',
                  'id': 'hp_scythe_port_front',
                  'position': [-1.6, -0.05, 1.2],
                  'slot': 'launcher',
                  'tracking_speed': 210},
                 {'gimbal': 28,
                  'group': 'primary',
                  'id': 'hp_scythe_port_rear',
                  'position': [-1.2, -0.02, -0.2],
                  'slot': 'cannon',
                  'tracking_speed': 190},
                 {'gimbal': 32,
                  'group': 'aux',
                  'id': 'hp_scythe_starboard_front',
                  'position': [1.6, -0.05, 1.2],
                  'slot': 'launcher',
                  'tracking_speed': 210},
                 {'gimbal': 28,
                  'group': 'primary',
                  'id': 'hp_scythe_starboard_rear',
                  'position': [1.2, -0.02, -0.2],
                  'slot': 'cannon',
                  'tracking_speed': 190}],
  'id': 'scythe_interceptor',
  'level_requirement': 1,
  'name': 'Scythe',
  'notes': 'Smallest Colonial escort hull tuned for high thrust-to-mass and fast '
           'response. Interceptor role (engine-heavy). No level requirement in '
           'this build despite in-game notice.',
  'role': 'Interceptor',
  'role_bonuses': ['Interceptor role receives additional Engine slots; Advanced '
                   'Scythe gains +1 Engine slot.'],
  'size': 'Escort',
  'slots': {'computer': 2,
            'engine': {'advanced_delta': 1, 'advanced_total': 5, 'base': 4},
            'hull': 2,
            'weapons': {'weapons': 4,
                        'guns': 0,
                        'launchers': 0,
                        'defensive': 0,
                        'special': 0}},
  'stats': {'acceleration': 5,
            'armor_value': 25,
            'avoidance_fading': 0.75,
            'avoidance_rating': 290,
            'boost_acceleration': 1.5,
            'boost_cost': 1.5,
            'boost_speed': 60,
            'critical_defense': 80,
            'dradis_range_base': 1250,
            'dradis_range_max': 2500,
            'durability': 14000,
            'durability_bonus': 0,
            'emitter_rating': 100,
            'firewall_rating': 100,
            'ftl_charge_time': 20,
            'ftl_cooldown': 35,
            'ftl_cost': 80,
            'ftl_range': 6.75,
            'hull_points': 1400,
            'hull_recovery_per_sec': 7.8,
            'inertial_compensation': 50,
            'max_radiation_level': 140,
            'pitch_acceleration': 25,
            'pitch_speed': 25,
            'power_points': 200,
            'power_recovery_per_sec': 10,
            'radioactive_decay': 0.9,
            'radioresistance': 0,
            'roll_acceleration': 50,
            'roll_speed': 50,
            'speed': 40,
            'strafe_acceleration': 0,
            'strafe_speed': 0,
            'transponder_power_cost': 0,
            'turn_accel': 25,
            'turn_rate': 25,
            'visual_range': 250,
            'yaw_acceleration': 25,
            'yaw_speed': 25},
  'traits': ['Smallest Colonial Escort tuned for rapid intercepts and fast '
             'response.',
            'Snappy handling backed by 25 deg/s turn rates and acceleration.',
            'Engine-focused layout supports sustained pursuit capability.'],
  'upgrade_to': 'advanced_scythe'},
 {'counterpart': None,
  'economy': {'operating': {'boost': 2.1, 'ftl': 80}, 'purchase': {'cubits': 600000}},
  'equipment': {'modules': {},
                'weapons': {'hp_maul_port_aft': 'mec_e13',
                            'hp_maul_port_forward': 'hd_m63p',
                            'hp_maul_spinal': 'hd_m50p',
                            'hp_maul_starboard_aft': 'mec_e13',
                            'hp_maul_starboard_forward': 'hd_m63p'}},
  'faction': 'Colonial Fleet',
  'hardpoints': [{'gimbal': 34,
                  'group': 'aux',
                  'id': 'hp_maul_port_forward',
                  'position': [-2.2, -0.1, 1.8],
                  'slot': 'launcher',
                  'tracking_speed': 200},
                 {'gimbal': 34,
                  'group': 'aux',
                  'id': 'hp_maul_starboard_forward',
                  'position': [2.2, -0.1, 1.8],
                  'slot': 'launcher',
                  'tracking_speed': 200},
                 {'gimbal': 28,
                  'group': 'primary',
                  'id': 'hp_maul_port_aft',
                  'position': [-1.6, -0.05, -0.4],
                  'slot': 'cannon',
                  'tracking_speed': 170},
                 {'gimbal': 28,
                  'group': 'primary',
                  'id': 'hp_maul_starboard_aft',
                  'position': [1.6, -0.05, -0.4],
                  'slot': 'cannon',
                  'tracking_speed': 170},
                 {'gimbal': 24,
                  'group': 'special',
                  'id': 'hp_maul_spinal',
                  'position': [0.0, -0.2, 2.6],
                  'slot': 'launcher',
                  'tracking_speed': 160}],
  'id': 'maul_assault',
  'level_requirement': 1,
  'name': 'Maul',
  'notes': 'Sturdy, heavily armored escort optimized for close-in brawling and '
           'guard duty. Assault role favors extra Hull slots and strong '
           'baseline survivability over speed.',
  'role': 'Assault',
  'role_bonuses': ['Assault identity: gains more Hull slots than other Escorts; '
                   'Advanced Maul adds +1 Hull slot.'],
  'size': 'Escort',
  'slots': {'computer': 2,
            'engine': 2,
            'hull': {'advanced_delta': 1, 'advanced_total': 5, 'base': 4},
            'weapons': {'weapons': 4,
                        'guns': 0,
                        'launchers': 0,
                        'defensive': 0,
                        'special': 1}},
  'stats': {'acceleration': 4,
            'armor_value': 30,
            'avoidance_fading': 0.75,
            'avoidance_rating': 250,
            'boost_acceleration': 1.5,
            'boost_cost': 2.1,
            'boost_speed': 55,
            'critical_defense': 120,
            'dradis_range_base': 1250,
            'dradis_range_max': 3000,
            'durability': 16000,
            'durability_bonus': 0,
            'emitter_rating': 150,
            'firewall_rating': 150,
            'ftl_charge_time': 20,
            'ftl_cooldown': 32.5,
            'ftl_cost': 80,
            'ftl_range': 7.5,
            'hull_points': 2000,
            'hull_recovery_per_sec': 8.9,
            'inertial_compensation': 50,
            'max_radiation_level': 170,
            'pitch_acceleration': 20,
            'pitch_speed': 20,
            'power_points': 200,
            'power_recovery_per_sec': 10,
            'radioactive_decay': 1.1,
            'radioresistance': 0,
            'roll_acceleration': 30,
            'roll_speed': 30,
            'speed': 35,
            'strafe_acceleration': 0,
            'strafe_speed': 0,
            'transponder_power_cost': 0,
            'turn_accel': 20,
            'turn_rate': 20,
            'visual_range': 300,
            'yaw_acceleration': 20,
            'yaw_speed': 20},
  'traits': ['Largest of the three Escort frames with reinforced plating and high '
             'durability.',
            'Best employed as a frontline screen or station guard supporting '
            'Command escorts.',
            'Slowest Escort handling leaves it vulnerable to kiting and EW '
            'pressure if isolated.'],
  'upgrade_to': 'advanced_maul'},
 {'counterpart': 'Hel',
  'economy': {'operating': {'boost': 5.4, 'ftl': 250},
              'purchase': {'tylium': 2000000},
              'upgrade': {}},
  'equipment': {'modules': {},
                'weapons': {'hp_vanir_aft': 'mec_l39f',
                            'hp_vanir_fore': 'mec_l35',
                            'hp_vanir_launcher_port': 'hd_h40',
                            'hp_vanir_launcher_starboard': 'hd_h48',
                            'hp_vanir_port': 'mec_l34',
                            'hp_vanir_starboard': 'mec_l34'}},
  'faction': 'Colonial Fleet',
  'hardpoints': [{'gimbal': 30,
                  'group': 'primary',
                  'id': 'hp_vanir_fore',
                  'position': [0.0, 0.4, 5.4],
                  'slot': 'cannon',
                  'tracking_speed': 160},
                 {'gimbal': 35,
                  'group': 'primary',
                  'id': 'hp_vanir_port',
                  'position': [-2.4, 0.2, 3.2],
                  'slot': 'cannon',
                  'tracking_speed': 150},
                 {'gimbal': 35,
                  'group': 'primary',
                  'id': 'hp_vanir_starboard',
                  'position': [2.4, 0.2, 3.2],
                  'slot': 'cannon',
                  'tracking_speed': 150},
                 {'gimbal': 28,
                  'group': 'primary',
                  'id': 'hp_vanir_aft',
                  'position': [0.0, 0.2, -2.8],
                  'slot': 'cannon',
                  'tracking_speed': 140},
                 {'gimbal': 35,
                  'group': 'aux',
                  'id': 'hp_vanir_launcher_port',
                  'position': [-1.6, -0.6, 1.2],
                  'slot': 'launcher',
                  'tracking_speed': 140},
                 {'gimbal': 35,
                  'group': 'aux',
                  'id': 'hp_vanir_launcher_starboard',
                  'position': [1.6, -0.6, 1.2],
                  'slot': 'launcher',
                  'tracking_speed': 140}],
  'id': 'vanir_command',
  'level_requirement': 1,
  'name': 'Vanir',
  'notes': 'Line-class command hull that acts as a mobile anchor for missile and '
           'energy-support operations.',
  'role': 'Command',
  'role_bonuses': ['Role Bonus: −150 Transponder Power Cost (Command bonus).'],
  'size': 'Line',
  'slots': {'computer': 4,
            'engine': 2,
            'hull': 2,
            'weapons': {'weapons': 6, 'guns': 4, 'launchers': 2, 'defensive': 0}},
  'stats': {'acceleration': 2,
            'armor_value': 40,
            'avoidance_fading': 0.75,
            'avoidance_rating': 50,
            'boost_acceleration': 1.5,
            'boost_cost': 5.4,
            'boost_speed': 42.5,
            'critical_defense': 100,
            'dradis_range_base': 1500,
            'dradis_range_max': 4000,
            'durability': 35000,
            'durability_bonus': 0.4,
            'emitter_rating': 200,
            'firewall_rating': 200,
            'ftl_charge_time': 25,
            'ftl_cooldown': 30,
            'ftl_cost': 250,
            'ftl_range': 11,
            'hull_points': 3500,
            'hull_recovery_per_sec': 19.4,
            'inertial_compensation': 50,
            'max_radiation_level': 220,
            'pitch_acceleration': 9,
            'pitch_speed': 9,
            'power_points': 650,
            'power_recovery_per_sec': 28,
            'radioactive_decay': 1.4,
            'radioresistance': 0,
            'roll_acceleration': 9,
            'roll_speed': 9,
            'speed': 27.5,
            'strafe_acceleration': 0,
            'strafe_speed': 0,
            'transponder_power_cost': -150,
            'turn_accel': 9,
            'turn_rate': 9,
            'visual_range': 1000,
            'yaw_acceleration': 9,
            'yaw_speed': 9},
  'traits': ['Heavy Command line ship with a large energy pool and strong computer '
             'capacity for EW/support builds.',
             'Plays as a mobile anchor: slow handling but durable with solid '
             'long-range sensors; excels when screened by Escorts/Strikes and when '
             'fielded as a missile/energy-support platform.'],
  'upgrade_to': 'advanced_vanir'},
 {'counterpart': None,
  'economy': {'operating': {'boost': 18, 'ftl': 30},
              'purchase': {'tylium': 400000},
              'upgrade': {}},
  'equipment': {'modules': {'computer': []}, 'weapons': {}},
  'faction': 'Colonial Fleet',
  'hardpoints': [{'facing': 'forward',
                  'gimbal': 35,
                  'group': 'primary',
                  'id': 'hp_brimir_forward_center',
                  'position': [0.0, 0.6, 13.5],
                  'slot': 'gun',
                  'tracking_speed': 120},
                 {'facing': 'forward',
                  'gimbal': 32,
                  'group': 'primary',
                  'id': 'hp_brimir_forward_port',
                  'position': [-2.8, 0.5, 12.8],
                  'slot': 'gun',
                  'tracking_speed': 115},
                 {'facing': 'forward',
                  'gimbal': 32,
                  'group': 'primary',
                  'id': 'hp_brimir_forward_starboard',
                  'position': [2.8, 0.5, 12.8],
                  'slot': 'gun',
                  'tracking_speed': 115},
                 {'facing': 'up',
                  'gimbal': 40,
                  'group': 'primary',
                  'id': 'hp_brimir_dorsal_turret',
                  'position': [0.0, 2.2, 6.5],
                  'slot': 'gun',
                  'tracking_speed': 110},
                 {'facing': 'left',
                  'gimbal': 55,
                  'group': 'aux',
                  'id': 'hp_brimir_port_launcher',
                  'position': [-5.6, 0.3, 4.4],
                  'slot': 'launcher',
                  'tracking_speed': 105},
                 {'facing': 'right',
                  'gimbal': 55,
                  'group': 'aux',
                  'id': 'hp_brimir_starboard_launcher',
                  'position': [5.6, 0.3, 4.4],
                  'slot': 'launcher',
                  'tracking_speed': 105},
                 {'facing': 'left',
                  'gimbal': 60,
                  'group': 'defense',
                  'id': 'hp_brimir_port_pd_fore',
                  'position': [-5.2, 0.8, 9.0],
                  'slot': 'defensive',
                  'tracking_speed': 160},
                 {'facing': 'left',
                  'gimbal': 60,
                  'group': 'defense',
                  'id': 'hp_brimir_port_pd_aft',
                  'position': [-5.0, 0.5, 0.5],
                  'slot': 'defensive',
                  'tracking_speed': 150},
                 {'facing': 'right',
                  'gimbal': 60,
                  'group': 'defense',
                  'id': 'hp_brimir_starboard_pd_fore',
                  'position': [5.2, 0.8, 9.0],
                  'slot': 'defensive',
                  'tracking_speed': 160},
                 {'facing': 'right',
                  'gimbal': 60,
                  'group': 'defense',
                  'id': 'hp_brimir_starboard_pd_aft',
                  'position': [5.0, 0.5, 0.5],
                  'slot': 'defensive',
                  'tracking_speed': 150},
                 {'facing': 'forward',
                  'gimbal': 35,
                  'group': 'special',
                  'id': 'hp_brimir_special_fore',
                  'position': [0.0, -0.2, 10.8],
                  'slot': 'gun',
                  'tracking_speed': 120},
                 {'facing': 'aft',
                  'gimbal': 35,
                  'group': 'special',
                  'id': 'hp_brimir_special_aft',
                  'position': [0.0, -0.2, -2.5],
                  'slot': 'gun',
                  'tracking_speed': 120},
                 {'facing': 'left',
                  'gimbal': 45,
                  'group': 'special',
                  'id': 'hp_brimir_special_port',
                  'position': [-4.0, -0.1, 6.0],
                  'slot': 'gun',
                  'tracking_speed': 125},
                 {'facing': 'right',
                  'gimbal': 45,
                  'group': 'special',
                  'id': 'hp_brimir_special_starboard',
                  'position': [4.0, -0.1, 6.0],
                  'slot': 'gun',
                  'tracking_speed': 125}],
  'id': 'brimir_carrier',
  'level_requirement': 40,
  'name': 'Brimir',
  'notes': ('Discovery of the derelict shipyards near Delta Canopis has allowed the '
            'construction of the Brimir-class carrier. The carrier is a support and '
            'logistics vessel that allows strike ships to coordinate attacks and '
            'quickly repair and refit away from an outpost.'),
  'role': 'Carrier',
  'role_bonuses': ['Carrier logistics network enables mobile repair and refit support '
                   'for allied squadrons.'],
  'size': 'Capital',
  'slots': {'computer': 3,
            'engine': 2,
            'hull': 0,
            'weapons': {'weapons': 0,
                        'defensive': 4,
                        'guns': 8,
                        'launchers': 2}},
  'stats': {'acceleration': 3,
            'armor_value': 40,
            'avoidance_fading': 0.75,
            'avoidance_rating': 20,
            'boost_acceleration': 1.5,
            'boost_cost': 18,
            'boost_speed': 30,
            'critical_defense': 150,
            'dradis_range_base': 2000,
            'dradis_range_max': 4500,
            'durability': 100000,
            'durability_bonus': 0.5,
            'emitter_rating': 240,
            'firewall_rating': 240,
            'ftl_charge_time': 30,
            'ftl_cooldown': 34,
            'ftl_cost': 30,
            'ftl_range': 12,
            'hull_points': 8000,
            'hull_recovery_per_sec': 40,
            'inertial_compensation': 44,
            'max_radiation_level': 240,
            'pitch_acceleration': 9,
            'pitch_speed': 9,
            'power_points': 1000,
            'power_recovery_per_sec': 40,
            'radioactive_decay': 1.5,
            'radioresistance': 0,
            'roll_acceleration': 8,
            'roll_speed': 8,
            'speed': 18,
            'strafe_acceleration': 0,
            'strafe_speed': 0,
            'transponder_power_cost': 0,
            'turn_accel': 9,
            'turn_rate': 8,
            'visual_range': 1750,
            'yaw_acceleration': 9,
            'yaw_speed': 9},
  'traits': ['Carrier-class Capital ship optimized for fleet support and strike '
             'coordination.',
             'Provides mobile repair and refit capabilities for allied Strike and '
             'Escort craft while operating away from outposts.',
             'Balanced defensive armament (8 guns, 2 launchers, and 4 defensive '
             'weapons) allows it to defend itself without matching a battleship’s '
             'raw damage output.',
             'Moderate FTL reach (12 LY) for a Capital ship—adequate for long-range '
             'deployments.',
             'Excellent energy and EW suite (1,000 capacity, 40/s recovery) supports '
             'sustained drone operations, PD systems, and EW defenses.',
             'Limited agility (8–9°/s turning) and minimal avoidance (20) — relies on '
             'escorts and fleet positioning for protection.',
             'Command-center design enables coordination bonuses when operating near '
             'allied squadrons (if your fleet aura systems model these).',
             'Armor (40) and Critical Defense (150) values make it resilient against '
             'both kinetic and energy weapon fire.'],
  'upgrade_to': 'advanced_brimir'},
 {'counterpart': None,
  'economy': {'operating': {'boost': 20, 'ftl': 32},
              'purchase': {'tylium': 460000},
              'upgrade': {'tylium': 150000}},
  'equipment': {'modules': {'computer': []},
                'weapons': {'hp_thorim_spinal': 'pol_x01'}},
  'faction': 'Colonial Fleet',
  'hardpoints': [{'facing': 'forward',
                  'gimbal': 26,
                  'group': 'primary',
                  'id': 'hp_thorim_spinal',
                  'position': [0.0, 0.4, 11.2],
                  'slot': 'gun',
                  'tracking_speed': 102},
                 {'facing': 'forward',
                  'gimbal': 24,
                  'group': 'primary',
                  'id': 'hp_thorim_port_inner',
                  'position': [-4.6, 0.2, 9.6],
                  'slot': 'gun',
                  'tracking_speed': 104},
                 {'facing': 'forward',
                  'gimbal': 24,
                  'group': 'primary',
                  'id': 'hp_thorim_port_outer',
                  'position': [-6.8, 0.1, 6.4],
                  'slot': 'gun',
                  'tracking_speed': 100},
                 {'facing': 'forward',
                  'gimbal': 24,
                  'group': 'primary',
                  'id': 'hp_thorim_starboard_inner',
                  'position': [4.6, 0.2, 9.6],
                  'slot': 'gun',
                  'tracking_speed': 104},
                 {'facing': 'forward',
                  'gimbal': 24,
                  'group': 'primary',
                  'id': 'hp_thorim_starboard_outer',
                  'position': [6.8, 0.1, 6.4],
                  'slot': 'gun',
                  'tracking_speed': 100}],
  'id': 'thorim_siege',
  'level_requirement': 44,
  'name': 'Thorim Siege Ship',
  'notes': ('The Thorim-class siege ship traces its lineage to heavy planetary '
            'bombardment barges. Reinforced crescent spars focus massive plasma '
            'lances while a recessed engine cradle keeps the firing gap clear.'),
  'role': 'Siege',
  'role_bonuses': ['Station-keeping algorithms tighten plasma dispersion after holding '
                   'position for 3 seconds.'],
  'size': 'Capital',
  'slots': {'computer': 2,
            'engine': 3,
            'hull': 3,
            'weapons': {'weapons': 5, 'defensive': 0, 'guns': 5, 'launchers': 0}},
  'stats': {'acceleration': 2.6,
            'armor_value': 55,
            'avoidance_fading': 0.72,
            'avoidance_rating': 15,
            'boost_acceleration': 1.2,
            'boost_cost': 20,
            'boost_speed': 24,
            'critical_defense': 180,
            'dradis_range_base': 2200,
            'dradis_range_max': 5200,
            'durability': 120000,
            'durability_bonus': 0.6,
            'emitter_rating': 260,
            'firewall_rating': 220,
            'ftl_charge_time': 34,
            'ftl_cooldown': 38,
            'ftl_cost': 32,
            'ftl_range': 14,
            'hull_points': 9200,
            'hull_recovery_per_sec': 32,
            'inertial_compensation': 36,
            'max_radiation_level': 260,
            'pitch_acceleration': 7,
            'pitch_speed': 7,
            'power_points': 1150,
            'power_recovery_per_sec': 38,
            'radioactive_decay': 1.6,
            'radioresistance': 0,
            'roll_acceleration': 6,
            'roll_speed': 6,
            'speed': 14,
            'strafe_acceleration': 0,
            'strafe_speed': 0,
            'transponder_power_cost': 0,
            'turn_accel': 7,
            'turn_rate': 6,
            'visual_range': 1650,
            'yaw_acceleration': 7,
            'yaw_speed': 7},
  'traits': ['Long-range siege platform built around a recessed spinal plasma cannon '
             'and five forward gun hardpoints.',
             'Best-in-class crescent firing arc keeps the frontal gap clear for '
             'super-heavy plasma volleys.',
             'Reinforced hull ribs grant above-average armor while triple engine '
             'pylons stabilise recoil but limit agility.'],
  'upgrade_to': 'advanced_thorim'},
 {'counterpart': None,
  'economy': {'operating': {'boost': 0, 'ftl': 0},
              'purchase': {'tylium': 0},
              'upgrade': {'level': 0, 'tylium': 0}},
  'equipment': {'modules': {'computer': ['eccm_mk1',
                                         'jammer_mk1',
                                         'point_defense_mk1',
                                         'flare_launcher_mk1']},
                'weapons': {'hp_outpost_east': 'hd_h48',
                            'hp_outpost_launcher_port': 'ram_179a',
                            'hp_outpost_launcher_starboard': 'ram_179a',
                            'hp_outpost_north': 'hd_m50p',
                            'hp_outpost_pd_east': 'pd_x30p',
                            'hp_outpost_pd_north': 'ram_179a',
                            'hp_outpost_pd_south': 'ram_179a',
                            'hp_outpost_pd_west': 'pd_x30p',
                            'hp_outpost_south': 'hd_m63',
                            'hp_outpost_west': 'hd_h48'}},
  'faction': 'Colonial Fleet',
  'hardpoints': [{'gimbal': 35,
                  'group': 'primary',
                  'id': 'hp_outpost_north',
                  'position': [-70.0, 32.0, 600.0],
                  'slot': 'launcher',
                  'tracking_speed': 36},
                 {'gimbal': 35,
                  'group': 'primary',
                  'id': 'hp_outpost_south',
                  'position': [70.0, 32.0, 600.0],
                  'slot': 'launcher',
                  'tracking_speed': 36},
                 {'gimbal': 42,
                  'group': 'primary',
                  'id': 'hp_outpost_east',
                  'position': [248.0, 42.0, -40.0],
                  'slot': 'launcher',
                  'tracking_speed': 32},
                 {'gimbal': 42,
                  'group': 'primary',
                  'id': 'hp_outpost_west',
                  'position': [-248.0, 42.0, -40.0],
                  'slot': 'launcher',
                  'tracking_speed': 32},
                 {'gimbal': 180,
                  'group': 'aux',
                  'id': 'hp_outpost_launcher_port',
                  'position': [-235.0, -50.0, -260.0],
                  'slot': 'launcher',
                  'tracking_speed': 24},
                 {'gimbal': 180,
                  'group': 'aux',
                  'id': 'hp_outpost_launcher_starboard',
                  'position': [235.0, -50.0, -260.0],
                  'slot': 'launcher',
                  'tracking_speed': 24},
                 {'gimbal': 180,
                  'group': 'aux',
                  'id': 'hp_outpost_pd_north',
                  'position': [220.0, -42.0, 60.0],
                  'slot': 'launcher',
                  'tracking_speed': 180},
                 {'gimbal': 180,
                  'group': 'aux',
                  'id': 'hp_outpost_pd_south',
                  'position': [-220.0, -42.0, 60.0],
                  'slot': 'launcher',
                  'tracking_speed': 180},
                 {'gimbal': 180,
                  'group': 'defense',
                  'id': 'hp_outpost_pd_east',
                  'position': [205.0, 38.0, 200.0],
                  'slot': 'defensive',
                  'tracking_speed': 180},
                 {'gimbal': 180,
                  'group': 'defense',
                  'id': 'hp_outpost_pd_west',
                  'position': [-205.0, 38.0, 200.0],
                  'slot': 'defensive',
                  'tracking_speed': 180}],
  'id': 'outpost_regular',
  'level_requirement': 0,
  'name': 'Aegis System Outpost',
  'notes': 'Permanent sector outpost used for testing deployment logic.',
  'role': 'Station',
  'role_bonuses': ['Projects a logistics hub that anchors control of the sector.'],
  'size': 'Outpost',
  'slots': {'computer': 6,
            'engine': 0,
            'hull': 6,
            'weapons': {'defensive': 2, 'guns': 0, 'launchers': 8}},
  'stats': {'acceleration': 0,
            'armor_value': 160,
            'avoidance_fading': 0.75,
            'avoidance_rating': 15,
            'boost_acceleration': 0,
            'boost_cost': 0,
            'boost_speed': 0,
            'critical_defense': 220,
            'dradis_range_base': 4000,
            'dradis_range_max': 6500,
            'durability': 250000,
            'durability_bonus': 0,
            'emitter_rating': 280,
            'firewall_rating': 420,
            'ftl_charge_time': 0,
            'ftl_cooldown': 0,
            'ftl_cost': 0,
            'ftl_range': 0,
            'hull_points': 24000,
            'hull_recovery_per_sec': 18,
            'inertial_compensation': 1.2,
            'max_radiation_level': 0,
            'pitch_acceleration': 4,
            'pitch_speed': 6,
            'power_points': 2400,
            'power_recovery_per_sec': 120,
            'radioactive_decay': 0,
            'radioresistance': 0,
            'roll_acceleration': 4,
            'roll_speed': 6,
            'speed': 0,
            'strafe_acceleration': 0,
            'strafe_speed': 0,
            'transponder_power_cost': 0,
            'turn_accel': 4,
            'turn_rate': 6,
            'visual_range': 2200,
            'yaw_acceleration': 4,
            'yaw_speed': 6},
  'traits': ['Stationary battle station with wide firing arcs and embedded PD grids.',
             'Serves as a jump beacon and services hub when active.'],
  'upgrade_to': None}]
